const data = {
  item44: {
    id: "44",
    title: "En el modelo TCP/IP para LAN indica cual es el nuevo nivel definido:",
    first: "Transporte",
    second: "Enlace de datos",
    third: "Acceso al medio",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item45: {
    id: "45",
    title: "El protocolo X25 es un ejemplo de protocolo de nivel ...",
    first: "Físico",
    second: "Enlace",
    third: "Red",
    fourth: "Transporte",
    answer: 3,
  },
  item46: {
    id: "46",
    title: "Indica cual de los siguientes NO es uno de los principios definidos para la creación del modelo OSI:",
    first: "Cada capa debe realizar una función bien definida.",
    second: "La función de cada capa se debe elegir con la intención de definir protocolos estandarizados internacionalmente.",
    third: "Los límites de las capas se deben elegir a fin de minimizar el flujo de información a través de las interfaces.",
    fourth: "La cantidad de capas debe ser suficientemente pequeña para no tener que agrupar funciones distintas en la misma capa y lo bastante grande para que la arquitectura no se vuelva inmanejable.",
    answer: 4,
  },
  item47: {
    id: "47",
    title: "El medio de transmisión recomendado para FastEthernet es:",
    first: "UTP Categoría 3",
    second: "UTP Categoría 4",
    third: "UTP Categoría 5E y 6",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item48: {
    id: "48",
    title: "De las siguientes topologías, indica cual de ellas es mas robusta frente a la caída de enlaces:",
    first: "Bus",
    second: "Anillo",
    third: "Estrella",
    fourth: "Malla",
    answer: 4,
  },
  item49: {
    id: "49",
    title: "Un hub tiene...",
    first: "Topología física en estrella y lógica en bus",
    second: "Topología física y lógica en bus",
    third: "Topología lógica en estrella y física en bus",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item50: {
    id: "50",
    title: "Las redes de comunicaciones de fibra que se están extendiendo en las ciudades se clasifican como redes:",
    first: "MAN",
    second: "LAN",
    third: "WAN",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item51: {
    id: "51",
    title: "El protocolo SONET es un ejemplo de protocolo aplicado a redes:",
    first: "MAN",
    second: "LAN",
    third: "WAN",
    fourth: "PAN",
    answer: 3,
  },
  item52: {
    id: "52",
    title: "De forma general, las redes más pequeñas localizadas en una misma área geográfica tienden a utilizar:",
    first: "Enlaces de difusión",
    second: "Enlaces de punto a punto",
    third: "Enlaces en anillo",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item53: {
    id: "53",
    title: "El protocolo IP es un ejemplo de:",
    first: "Conmutación de paquetes en modo Circuito Virtual",
    second: "Conmutación de paquetes en modo Datagrama",
    third: "Conmutación de circuitos en modo Datagrama",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item54: {
    id: "54",
    title: "La gran mayoría de redes de comunicaciones de datos utilizan:",
    first: "Conmutación de circuitos en modo Circuito Virtual",
    second: "Conmutación de circuitos en modo datagrama",
    third: "Conmutación de paquetes",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item55: {
    id: "55",
    title: "Las redes telefónicas son un ejemplo de:",
    first: "Conmutación de paquetes en modo Circuito Virtual",
    second: "Conmutación de circuitos en modo datagrama",
    third: "Conmutación de circuitos",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item56: {
    id: "56",
    title: "Si la estación A con IP 126.25.25.23/23 realiza un ping a B con IP 126.25.24.1/23...",
    first: "Sería entrega indirecta, por lo que se enviaría al Router",
    second: "Sería entrega directa",
    third: "No se puede enviar el datagrama por ser una IP de destino errónea",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item57: {
    id: "57",
    title: "El campo en IPv4 que indica la posición del fragmento dentro del datagrama original se denomina:",
    first: "ID",
    second: "Offset",
    third: "MF",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item58: {
    id: "58",
    title: "El protocolo que permite obtener la dirección física a partir de la dirección lógica se denomina:",
    first: "DHCP",
    second: "RARP",
    third: "ARP",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item59: {
    id: "59",
    title: "Indica cuál de las siguientes direcciones pertenece a una dirección de IPv4 privada:",
    first: "122.32.12.0",
    second: "172.15.25.1",
    third: "172.31.22.13",
    fourth: "Todas son dirección públicas",
    answer: 3,
  },
  item60: {
    id: "60",
    title: "Indica el número de bits de una dirección IPv4 de clase B:",
    first: "8",
    second: "16",
    third: "24",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item61: {
    id: "61",
    title: "Respecto al switch, indica la afirmación errónea:",
    first: "Un Switch/Puente expande el Dominio de Difusión",
    second: "Un Switch/Puente segmenta el Dominio de Colisión",
    third: "Los conmutadores Fragment Free esperan a recibir los primeros 1500 bytes para evitar retransmisión de colisiones",
    fourth: "En un switch, si no conoce el puerto de destino, realiza inundación",
    answer: 3,
  },
  item62: {
    id: "62",
    title: "El modo de funcionamiento de un switch más utilizado en redes corporativas que implementan siempre el control de errores es:",
    first: "Store-and-Forward",
    second: "Cut-Through",
    third: "Adaptative Cut-Through",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item63: {
    id: "63",
    title: "Un hub proporciona un ancho de banda de, por ejemplo, 100Mbps,",
    first: "Dedicado",
    second: "Compartido",
    third: "Exclusivo",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item64: {
    id: "64",
    title: "El repetidor es considerado un dispositivo de nivel:",
    first: "De acceso al medio",
    second: "De interfaz",
    third: "Físico",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item65: {
    id: "65",
    title: "Definiremos un dominio de difusión como ....",
    first: "El área de una red, formada por computadoras y dispositivos de red que se puede alcanzar enviando una trama broadcast.",
    second: "El área de una red, formada por computadoras y dispositivos de red que se puede alcanzar enviando una trama multicast.",
    third: "Un segmento físico de una red de computadores donde es posible que las tramas puedan 'colisionar' con otras.",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item66: {
    id: "66",
    title: "El estado inicial de todos los puertos cuando se inicia el switch es :",
    first: "Bloqueado",
    second: "Escucha",
    third: "Aprendizaje",
    fourth: "Envío",
    answer: 1,
  },
  item67: {
    id: "67",
    title: "Respecto al tiempo de vida en los datagramas de IPv4, selecciona la respuesta errónea:",
    first: "Los datagramas tienen un tiempo limitado de permanencia en la internet",
    second: "Cada retransmisión del datagrama (en cada router) debe decrementar el valor del campo",
    third: "Al llegar a cero el datagrama se descarta y ya no es retransmitido",
    fourth: "La finalidad es evitar redes demasiado grandes o con un nº muy alto de routers entre dos hosts",
    answer: 4,
  },
  item68: {
    id: "68",
    title: "La dirección 172.16.12.0/16 es:",
    first: "Una dirección de host privada",
    second: "Una dirección de host pública",
    third: "Una dirección de red privada",
    fourth: "Ninguna de las Anteriores",
    answer: 3,
  },
  item69: {
    id: "69",
    title: "Si tenemos la red 82.12.128.0/18 y debemos segmentar en 4 subredes, indica la dirección de la segunda subred:",
    first: "82.12.128.0",
    second: "82.12.192.0",
    third: "82.12.160.0",
    fourth: "82.12.224.0",
    answer: 3,
  },
  item70: {
    id: "70",
    title: "En IPv4, la dirección 132.128.14.0 es una dirección de:",
    first: "Host",
    second: "Broadcast",
    third: "Red",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item71: {
    id: "71",
    title: "El gran problema existente en las redes de acceso por medio compartido en bus es:",
    first: "La falta de escalabilidad",
    second: "El elevado retardo",
    third: "El elevado coste",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item72: {
    id: "72",
    title: "Respecto a una topología en estrella indica la afirmación errónea:",
    first: "La mayoría de redes Ethernet y Anillo están implementadas mediante topología en Estrella",
    second: "Proporciona una administración y actualización más cómoda",
    third: "Un hub proporciona topología física en estrella pero lógica de anillo",
    fourth: "La centralización implica un riesgo por único punto de fallo",
    answer: 3,
  },
  item73: {
    id: "73",
    title: "El valor del campo protocolo de una trama que contiene un datagrama IP debe valer:",
    first: "0x806",
    second: "0x800",
    third: "0x608",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item74: {
    id: "74",
    title: "El tamaño máximo de datos en un datagrama IP es:",
    first: "1500 bytes",
    second: "65535 bytes",
    third: "128 bytes",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item75: {
    id: "75",
    title: "Las PDU de nivel 2 se denominan:",
    first: "Bits",
    second: "Tramas",
    third: "Datagramas",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item76: {
    id: "76",
    title: "Las redes telefónicas son un ejemplo clásico de comunicaciones:",
    first: "De conmutación de paquetes en modo datagrama",
    second: "De conmutación de paquetes en modo circuito virtual",
    third: "De conmutación de paquetes en modo conmutación de circuitos",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item77: {
    id: "77",
    title: "El número de puertos disponibles en un switch se denomina:",
    first: "Agregado de Puertos",
    second: "Desempeño de Puertos",
    third: "Densidad de Puertos",
    fourth: "Ninguna de las Anteriores",
    answer: 3,
  },
  item78: {
    id: "78",
    title: "Si un datagrama con 1560 bytes de datos debe pasar por una red Ethernet con MTU por defecto, indica el tamaño máximo de datos IP en cada fragmento:",
    first: "1540",
    second: "1480",
    third: "1560",
    fourth: "Ninguna de las Anteriores",
    answer: 2,
  },
  item79: {
    id: "79",
    title: "Indica el valor mínimo y por defecto del campo longitud en la cabecera de un datagrama:",
    first: "20",
    second: "5",
    third: "32",
    fourth: "Ninguna de las Anteriores",
    answer: 1,
  },
  item80: {
    id: "80",
    title: "Si en el campo protocolo de una trama de Ethernet aparece 0x806, la parte de datos contiene el protocolo:",
    first: "ARP",
    second: "IP",
    third: "ICMP",
    fourth: "Ninguna de las Anteriores",
    answer: 1,
  },
  item81: {
    id: "81",
    title: "El estándar de Bluetooth se define para redes de tipo:",
    first: "LAN",
    second: "MAN",
    third: "PAN",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item82: {
    id: "82",
    title: "Los protocolos ATM o SONET son ejemplos de protocolos enfocados en redes de tipo:",
    first: "MAN",
    second: "PAN",
    third: "LAN",
    fourth: "Ninguna de las anteriores",
    answer: 4,
  },
  item83: {
    id: "83",
    title: "Indica el número de bits de host de una dirección IPv4 de clase A:",
    first: "16",
    second: "8",
    third: "24",
    fourth: "32",
    answer: 3,
  },
  item84: {
    id: "84",
    title: "Definiremos un dominio de colisión como ....",
    first: "El área de una red, formada por computadoras y dispositivos de red que se puede alcanzar enviando una trama broadcast.",
    second: "El área de una red, formada por computadoras y dispositivos de red que se puede alcanzar enviando una trama multicast.",
    third: "Un segmento físico de una red de computadores donde es posible que las tramas puedan 'colisionar' con otras.",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item85: {
    id: "85",
    title: "El modo de funcionamiento de un switch más utilizado en redes que exigen un retardo muy bajo a pesar de provocar retransmisión de colisiones es:",
    first: "Store-and-Forward",
    second: "Cut-Through",
    third: "Adaptative Cut-Through",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item86: {
    id: "86",
    title: "Indica el número de bits de una dirección IPv4 de clase A:",
    first: "24",
    second: "32",
    third: "8",
    fourth: "16",
    answer: 3,
  },
  item87: {
    id: "87",
    title: "El tipo de switch que espera recibir los primeros 64 bytes para enviar la retransmisión de colisiones se denomina:",
    first: "Store-and-Forward",
    second: "Cut-Through",
    third: "FragmentFree",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  }
};
      
