const data = {
  item1: {
    id: "1",
    title: "¿Qué objetivo principal tiene el diseño, desarrollo e implementación de un SIRH?",
    first: "Aumentar el tiempo dedicado a actividades transaccionales.",
    second:
      "Reducir el tiempo dedicado a actividades transaccionales.",
    third:
      "Disminuir la eficiencia en la gestión de recursos",
    fourth:
      "Mantener los métodos de gestión tradicionales.",
    answer: 2,
  },
  item2: {
    id: "2",
    title: "¿Qué representa el ciclo de vida de un empleado?",
    first: "Progresión a través de la organización desde la contratación hasta la separación.",
    second: " Únicamente el proceso de reclutamiento y selección.",
    third: "La formación y el desarrollo profesional exclusivamente",
    fourth: " Procesos administrativos sin inclusión de eventos personales.",
    answer: 1,
  },
  item3: {
    id: "3",
    title: "¿Qué se considera una actividad transaccional de RR.HH.?",
    first: "Cambio cultural.",
    second: "Mantenimiento de registros.",
    third: "Reorientación estratégica.",
    fourth: "Aumento de la innovación.",
    answer: 2,
  },
  item4: {
    id: "4",
    title: "¿Cuál es la definición de un Sistema de Gestión de Recursos Humanos (HRMS)?",
    first: "Un sistema que gestiona únicamente la nómina.",
    second: "Software que se enfoca exclusivamente en el reclutamiento.",
    third: "Una colección de procesos y aplicaciones que cubren la gestión de RRHH y la Tecnología de la Información. ",
    fourth: "Herramientas digitales para la comunicación interna solamente.",
    answer: 3,
  },
  item5: {
    id: "5",
    title: "¿Qué función no es proporcionada tradicionalmente por los sistemas HRMS?",
    first: "Contratación de empleados.",
    second: "Gestión de terminaciones/renuncias.",
    third: " Desarrollo de estrategias competitivas del mercado",
    fourth: "Pago a los empleados",
    answer: 3,
  },
  item6: {
    id: "6",
    title: "¿Qué es HRIS?",
    first: "Una política de RRHH.",
    second: "Un proceso de negocio.",
    third: "Un sistema que gestiona datos de empleados, ciclo de vida del empleado, entre otras funciones de RRHH. ",
    fourth: "Una plataforma de redes sociales para empleados.",
    answer: 3,
  },
  item7: {
    id: "7",
    title: "¿Cuál de las siguientes es una ventaja de implementar un SIRH?",
    first: " Aumento en el uso de papel.",
    second: "Reducción de la eficiencia operativa.",
    third: "Incremento en la satisfacción de los empleados. ",
    fourth: "Disminución en la calidad de la toma de decisiones.",
    answer: 3,
  },
  item8: {
    id: "8",
    title: "¿Cuál es una función básica de los SIRH?",
    first: "Desarrollo de cursos de formación",
    second: "Creación de contenido digital.",
    third: "Gestión de la nómina.",
    fourth: "Análisis avanzado de datos.",
    answer: 3,
  },
  item9: {
    id: "9",
    title: "¿Qué proceso es automatizado por los SIRH?",
    first: "Toma de decisiones ejecutivas.",
    second: "Selección de personal.",
    third: "Creación de estrategias empresariales",
    fourth: "Innovación de productos",
    answer: 2,
  },
  item10: {
    id: "10",
    title: "¿Cómo contribuyen los SIRH a la cultura organizacional?",
    first: "No tienen impacto en la cultura organizacional.",
    second: "Permiten la difusión de valores y políticas de la empresa. ",
    third: "Generan conflictos dentro de la organización.    ",
    fourth: "Reducen la comunicación interna.",
    answer: 2,
  },
  item11: {
    id: "11",
    title: "¿Cuál es un beneficio clave de los análisis de datos en SIRH?",
    first: "Incrementar la cantidad de datos almacenados.",
    second: "Mejorar la toma de decisiones estratégicas en RRHH.",
    third: "Disminuir la seguridad de los datos.",
    fourth: "Aumentar la complejidad de los sistemas",
    answer: 2,
  },
  item12: {
    id: "12",
    title: "En la implementación de un SIRH, ¿qué factor es crucial para el éxito a largo plazo?",
    first: "Elegir la solución más económica.",
    second: "Capacitación y adopción por parte de los usuarios.",
    third: "Limitar el acceso a la información.",
    fourth: "Reducir al mínimo las funcionalidades.",
    answer: 2,
  },
  item13: {
    id: "13",
    title: "¿Qué función avanzada ofrecen algunos SIRH para mejorar la gestión de talento?",
    first: "Seguimiento manual de la asistencia.",
    second: "Gestión automática de nóminas sin intervención humana.",
    third: "Herramientas de análisis predictivo para identificar necesidades de capacitación y desarrollo.",
    fourth: "Comunicación exclusivamente por correo electrónico.",
    answer: 3,
  },
  item14: {
    id: "14",
    title: "¿Qué ventaja ofrece un SIRH?",
    first: "Aumenta la necesidad de espacio físico.",
    second: "Mejora la eficiencia operativa",
    third: "Reduce la comunicación interna.",
    fourth: "Limita el acceso a información.",
    answer: 2,
  },
  item15: {
    id: "15",
    title: "¿Qué implica la 'gestión del ciclo de vida del empleado' en un SIRH?",
    first: "Solo la contratación y la formación.",
    second: "Exclusivamente el seguimiento del desempeño",
    third: "Desde la contratación hasta la retirada, incluyendo desarrollo y evaluación.",
    fourth: "Únicamente la administración de beneficios",
    answer: 3,
  },
  item16: {
    id: "16",
    title: "En el contexto de los SIRH, ¿qué representa un 'enfoque integrado'?",
    first: "Utilizar un único software para todas las tareas administrativas",
    second: "La combinación de gestión de recursos humanos y tecnología de la información para optimizar los procesos de RRHH.",
    third: "La segregación de las funciones de RRHH en diferentes plataformas.",
    fourth: "El uso exclusivo de herramientas manuales",
    answer: 2,
  },
  item17: {
    id: "17",
    title: "¿Qué característica de los SIRH permite una mejor adaptación a las leyes laborales locales?",
    first: "Configuración estática sin opciones de personalización",
    second: "Personalización y adaptabilidad en la configuración de políticas de RRHH. ",
    third: "Una única configuración válida internacionalmente",
    fourth: "Ausencia de actualizaciones de software.",
    answer: 2,
  },
  item18: {
    id: "18",
    title: "¿Cuál es un desafío común en la implementación de SIRH en una organización global?",
    first: "Simplificación excesiva de los procesos de negocio.",
    second: "Integración de diferentes culturas y prácticas laborales. ",
    third: "Reducción en la diversidad de herramientas de software.",
    fourth: "Aumento en la dependencia de métodos manuales.",
    answer: 2,
  },
  item19: {
    id: "19",
    title: "¿Qué papel juega la tecnología móvil en los SIRH modernos?",
    first: "Ninguno, ya que no es compatible con los SIRH.",
    second: "Solo para acceso administrativo",
    third: "Facilita el acceso remoto a la información de RRHH para los empleados.",
    fourth: "Únicamente para seguimiento de tiempo y asistencia",
    answer: 3,
  },
};