const data = {
    item1: {
      id: "1",
      title: "¿Cuántos accesos a disco hace falta para leer el nodo-i del directorio /usr/juegos/asesino en UNIX?",
      first: "8",
      second: "7",
      third: "5",
      fourth: "Ninguna de las anteriores",
      answer: 4,
    },
    item2: {
      id: "2",
      title: "En un sistema operativo se utiliza una estructura de nodos-i parecida a la Unix. El tamaño de bloque es de 1024 bytes y el tamaño de los punteros a bloques es de 32 bits. El nodo-i  tiene un cierto número de entradas de direccionamiento directo, una de direccionamiento indirecto simple y otra direccionamiento indirecto doble. Sabiendo que el tamaño máximo de un archivo es de 65800 Kbytes, ¿cuántas entradas directas hay en el i-nodo?",
      first: "10",
      second: "12",
      third: "8",
      fourth: "Ninguna de las anteriores",
      answer: 3,
    },
    item3: {
      id: "3",
      title: "¿Cuál de las siguientes no es una característica propia de las llamadas al sistema?",
      first: "Ofrece un servicio que implementa el S.O",
      second: "Durante su ejecución se ejecuta código del S.O",
      third: "El proceso que la realiza siempre retiene el uso del procesador hasta que termina.",
      fourth: "El proceso puede quedar bloqueado si la llamada lo exige.",
      answer: 3,
    },
    item4: {
      id: "4",
      title: "¿Cuál es la característica hardware más importante para poder implementar un Sistema Operativo Multitarea?",
      first: "Interrupciones procedentes de los dispositivos periféricos.",
      second: "Mecanismos hardware de protección de memoria.",
      third: "Dos modos de ejecución del procesador, modo usuario y modo privilegiado.",
      fourth: "Mecanismos de DMA para el intercambio de datos con los dispositivos.",
      answer: 3,
    },
    item5: {
      id: "5",
      title: "¿Qué carácter debe ser el primero en cada línea de comando de un fichero Makefile?",
      first: "Espacio en blanco",
      second: "Almohadilla #",
      third: "Tabulador",
      fourth: "El signo dólar $",
      answer: 3,
    },
    item6: {
      id: "6",
      title: "¿Qué hace este comando $ls -l?",
      first: "Obtiene un listado de un directorio",
      second: "Obtiene un listado ordenado alfabéticamente",
      third: "Genera un error",
      fourth: "Ninguna de las anteriores",
      answer: 1,
    },
    item7: {
      id: "7",
      title: "¿Cómo se llama la interfaz de programación de los sistemas tipo UNIX?",
      first: "Fedora",
      second: "Posix",
      third: "Win32",
      fourth: "Ninguna de las anteriores",
      answer: 2,
    },
    item8: {
      id: "8",
      title: "¿Cómo recibe el núcleo de un sistema operativo las notificaciones de sucesos de los periféricos?",
      first: "Señales de humo",
      second: "Pipes",
      third: "Interrupciones",
      fourth: "Ficheros",
      answer: 3,
    },
    item9: {
      id: "9",
      title: "Determine el espacio máximo (en bloques) que puede llegar a ocupar el mapa de bits de los bloques libres en un disco de 80 GB, usando un tamaño de bloque de 4KB y direcciones de bloque de 32 bits.",
      first: "640",
      second: "-1",
      third: "0",
      fourth: "2",
      answer: 1,
    },
    item10: {
      id: "10",
      title: "En una operación de lectura de un dispositivo utilizando E/S por DMA, la escritura en memoria del proceso que efectúa la operación de los datos leídos del dispositivo es realizada por:",
      first: "La CPU",
      second: "La controladora DMA",
      third: "La parte mecánica del dispositivo",
      fourth: "Ninguna de las opciones anteriores es correcta",
      answer: 2,
    },
    item11: {
      id: "11",
      title: "Cada entrada en un directorio tipo Unix, tiene dos columnas, una de ellas contiene el nombre del fichero o directorio, ¿Cuál es la otra columna?",
      first: "El número de dispositivo",
      second: "El puntero al bloque",
      third: "El número de INODO",
      fourth: "Ninguna de las anteriores",
      answer: 3,
    },
    item12: {
      id: "12",
      title: "¿Cuál de los siguientes atributos es heredado de su padre, por un proceso al ser UNIX?",
      first: "PID (process identifier)",
      second: "PPID (parent process identifier)",
      third: "PGID (process group identifier)",
      fourth: "Ninguno de ellos es heredado por el hijo",
      answer: 3,
    },
    item13: {
      id: "13",
      title: "En un sistema paginado, ¿cuál es el tamaño de un marco si el desplazamiento dentro de la página es de 10 bits?",
      first: "2^32 KB",
      second: "64 bits",
      third: "64 KB",
      fourth: "4 KB",
      answer: 4,
    },
    item14: {
      id: "14",
      title: "¿Cuánto puede avanzar como máximo el puntero del algoritmo del reloj de reemplazo de páginas durante la selección de una página?",
      first: "Ilimitado",
      second: "Una vuelta",
      third: "Es un parámetro ajustable por el usuario",
      fourth: "Dos vueltas",
      answer: 2,
    },
    item15: {
      id: "15",
      title: "Sean dos procesos P1 y P2 en FIFO con tiempo de conmutación de 5 ms. Si P1 (20 ms) llega primero y P2 (15 ms) después, ¿cuál es el tiempo de retorno de P1?",
      first: "30 ms",
      second: "40 ms",
      third: "45 ms",
      fourth: "50 ms",
      answer: 1,
    },
    item16: {
      id: "16",
      title: "El planificador a corto plazo selecciona un proceso...",
      first: "De entre los recién llegados para pasar a la cola de preparados",
      second: "De entre los de la cola de preparados para pasar a ejecución",
      third: "De entre los suspendidos en memoria principal para pasar a la cola de preparados",
      fourth: "De entre los suspendidos en memoria secundaria para pasar a la cola de preparados",
      answer: 2,
    },
    item17: {
      id: "17",
      title: "En la entrada/salida programada...",
      first: "El procesador solo interviene en la operación al principio y al final de la entrada/salida.",
      second: "Se utiliza el mecanismo de las interrupciones para comunicar el fin de la operación.",
      third: "El procesador se encarga de realizar la transferencia de datos entre el controlador del dispositivo y la memoria principal.",
      fourth: "Ninguna de las anteriores.",
      answer: 3,
    },
    item18: {
      id: "18",
      title: "¿Qué estrategia de asignación de memoria contigua genera más fragmentación externa?",
      first: "Primer ajuste",
      second: "Siguiente ajuste",
      third: "Mejor ajuste",
      fourth: "Peor ajuste",
      answer: 4,
    },
    item19: {
      id: "19",
      title: "Determine el espacio máximo que puede llegar a ocupar el mapa de bits de los bloques libres en un disco de 40 MB, usando un tamaño de bloque de 2 KB y direcciones de bloque de 16 bits.",
      first: "1",
      second: "21",
      third: "0",
      fourth: "2",
      answer: 4,
    },
    item20: {
      id: "20",
      title: "Indica cuál de las siguientes afirmaciones es CIERTA:",
      first: "La ENIAC se utilizó por el ejército de los EEUU durante la Primera Guerra Mundial",
      second: "John W. Mauchly and J. Presper Eckert diseñaron la arquitectura de la EDVAC",
      third: "John W. Mauchly and J. Presper Eckert publicaron el diseño de la arquitectura de la EDVAC",
      fourth: "La ENIAC estaba construida por medio de tubos de vacío y utilizaba lógica decimal",
      answer: 4,
    },
    item21: {
      id: "21",
      title: "En un sistema de gestión de memoria virtual con paginación, ¿cuántos fallos de página se han producido justo después de cargadas las cuatro primeras páginas de memoria?",
      first: "3 fallos de página",
      second: "4 fallos de página",
      third: "0 fallos de página",
      fourth: "5 fallos de página",
      answer: 2,
    },
    item22: {
      id: "22",
      title: "En la entrada/salida DMA (Acceso Directo a Memoria):",
      first: "El procesador se encarga de realizar la transferencia de datos entre el controlador del dispositivo y la memoria principal",
      second: "Se utiliza el mecanismo de las interrupciones para comunicar el fin de la operación",
      third: "El procesador sólo interviene en la operación al principio y al final de la entrada/salida.",
      fourth: "Ninguna de las anteriores",
      answer: 3,
    },
    item23: {
      id: "23",
      title: "Dado un espacio lógico de direcciones de 32 páginas de 1 Kbyte y una memoria física de 8 marcos de página, ¿cuántos bits hay en las direcciones físicas?",
      first: "13",
      second: "15",
      third: "32",
      fourth: "Ninguna de las anteriores",
      answer: 1,
    },
  };
  
