const data = {
item1: {
    id: "1",
    title: "La tecnología que permite alimentar mediante el par trenzado un dispositivo como un punto de acceso o un telefono voz IP se denomina:",
    first: "PLC",
    second: "PPTP",
    third: "PoE",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
item2: {
    id: "2",
    title: "Selecciona el protocolo introducido por el IEEE que permite una rápida convergencia de STP",
    first: "Ninguna de las anteriores",
    second: "FSTP",
    third: "RSTP",
    fourth: "RTP",
    answer: 3 ,
  },
item3: {
    id: "3",
    title: "El estado inicial de todos los puertos cuando se inicia el switch es",
    first: "Bloqueado",
    second: "Escucha",
    third: "Aprendizaje",
    fourth: "Envio",
    answer: 1,
  },
item4: {
    id: "4",
    title: "Respecto a las funciones de los puertos en STP, indique la afirmación errónea",
    first: "El puente raíz es elegido para la instancia de spanning-tree",
    second: "Todos los puentes tienen al menos un puerto raiz",
    third: "El puerto designado existe en los puentes raíz y en los que no son raíz",
    fourth: "El puerto no designado es aquel puerto de switch que está bloqueado",
    answer: 2,
  },
item5: {
    id: "5",
    title: "Cuando el tráfico de la red no puede ingresar ni salir del puerto, sin incluir las trama de unidad de datos del protocolo de puentes (BPDU) utilizadas por STP para evitar bucle, el puerto se considera",
    first: "Activo",
    second: "Aprendizaje",
    third: "Bloqueando",
    fourth: "Ninguna de las anterior",
    answer: 3,
  },
item6: {
    id: "6",
    title: "Indica la afirmación erronea respecto a la redundancia en redes jerárquicas",
    first: "La redundancia proporciona una gran flexibilidad en la eleccion de rutas de la red",
    second: "Permite que los datos se transmitan independientemente de la existencia de fallas en una sola ruta o en un dispositivo en las capas de distribucion o núcleo",
    third: "La redundancia cuenta con algunas complicaciones que deben ser tenidas en cuenta",
    fourth: "La redundancia no es necesaria gracias a la calidad actual de los dispositivos de red",
    answer: 4,
  },
item7: {
    id: "7",
    title: "Indica cual de las siguientes no es una caracteristica de los switches de capa de acceso",
    first: "Seguridad de puerto",
    second: "VLAN",
    third: "Agregado de enlaces",
    fourth: "Componentes redundantes",
    answer: 4,
  },
item8: {
    id: "8",
    title: "Dispositivos como un Punto de Acceso o un telefono IP, es como recomendable conectarlos a un switch con tecnología",
    first: "NAT",
    second: "IPv6",
    third: "PoE",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
item9: {
    id: "9",
    title: "Los switches que pueden interconectarse con el uso de un cable especial del backplane que otorga rendimiento de ancho de banda alto entre los switches se denominan",
    first: "Agregados",
    second: "Apilables",
    third: "Modulares",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item10: {
    id: "10",
    title: "El tiempo de envío de las actualizaciones STP se denomina",
    first: "Tiempo de saludo",
    second: "Retardo de envío",
    third: "Antigüedad máxima",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
item11: {
    id: "11",
    title: "El STA designa un único switch como puente raíz y lo utiliza como punto de referencia para todos los cálculos de rutas. Dicho puente raíz se elige a partir de",
    first: "Si pertenece a la capa de nucleo",
    second: "Su pertenencia a la capa de distribución",
    third: "De la prioridad que se define en el switch",
    fourth: "La elección es aleatoria",
    answer: 3,
  },
item12: {
    id: "12",
    title: "El conmutador que reenvía publicaciones VTP pero que no utiliza la configuración de VTP se denomina",
    first: "Servidor VTP",
    second: "Cliente VTP",
    third: "VTP Transparente",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
item13: {
    id: "13",
    title: "En las publicaciones de subconjunto de VTP, se publican",
    first: "Información de todas las VLAN configuradas",
    second: "La información de las VLANs modificadas",
    third: "Los puertos configurados con cada VLAN",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item14: {
    id: "14",
    title: "Respecto a las publicaciones de resumen de VTP indica la afirmación errónea",
    first: "Contiene el nombre de dominio del VTP, el número actual de revisión y otros detalles de la configuración del VTP",
    second: "Enviadas cada 5 minutos por el servidor",
    third: "Se envía inmediatamente cuando hay un cambio en el servidor o en alguno de los switches clientes",
    fourth: "Todas son ciertas",
    answer: 3,
  },
item15: {
    id: "15",
    title: "Respecto a los componentes de VTP, indica la afirmación errónea",
    first: "Todos los switches de una red conmutada comparten el mismo dominio",
    second: "VTP usa una jerarquía de publicaciones para distribuir y sincronizar las configuraciones de la VLAN a través de la red",
    third: "un switch se puede configurar en uno de tres modos: servidor, cliente o transparente.",
    fourth: "los servidores del VTP publican la información VLAN del dominio del VTP a otros switches",
    answer: 1,
  },
item16: {
    id: "16",
    title: "Indica cual de los siguientes no es un beneficio de VTP",
    first: "Consistencia en la configuración VLAN",
    second: "Seguimiento y monitorización",
    third: "Configuración de enlace troncal dinámico cuando las VLAN se agregan a la red",
    fourth: "Todos son beneficios de VTP",
    answer: 4,
  },
item17: {
    id: "17",
    title: "Indica la afirmación errónea de VTP",
    first: "Permite a un administrador de red configurar un switch de modo que propagará las configuraciones de la VLAN hacia los otros switches en la red",
    second: "Permite al administrador de red realizar cambios en un switch que está configurado como servidor del VT",
    third: "El servidor del VTP distribuye y sincroniza la información de la VLAN a todos los switches de la red conmutada",
    fourth: "El VTP guarda las configuraciones de la VLAN en la base de datos de la VLAN denominada vlan.dat",
    answer: 3,
  },
item18: {
    id: "18",
    title: "A medida que aumenta el tamaño de las redes",
    first: "La gestión de la VLAN se hace más sencilla y fácil",
    second: "La gestión de la VLAN se hace más compleja y costosa",
    third: "No afecta el tamaño a la gestión de VLAN",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item20: {
    id: "20",
    title: "En un enlace troncal, las siglas del campo indicativo de la pertenecia a una VLAN es",
    first: "FCS",
    second: "CFI",
    third: "VID",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
item21: {
    id: "21",
    title: "Respecto a los enlaces troncales de VLAN, indique la afirmación errónea",
    first: "Es un enlace punto a punto entre dos dispositivos de red que lleva más de una VLAN",
    second: "Un enlace troncal de VLAN no pertenece a una VLAN específica",
    third: "Cicso admite IEEE 802.1Q para la coordinación de enlaces troncales en interfaces Fast Ethernet y ATM",
    fourth: "Disminuye el cableado necesario entre switchs",
    answer: 3,
  },

  item22: {
    id: "22",
    title: "Para la comunicación intra VLAN es necesaria la presencia de ...",
    first: "únicamente un router",
    second: "un switch de capa 3 o un router",
    third: "ninguna entidad de nivel 3, unicamente una red conmutada",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item23: {
    id: "23",
    title: "Ante la presencia de VLANs, los dominios de broadcasts",
    first: "se expanden",
    second: "se fragmentan",
    third: "se solapan",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item24: {
    id: "24",
    title: "Si la asignación de la VLAN de un puerto se realiza por la MAC del dispositivo conectado a dicho puerto, nos encontramos ante un modo de pertenencia de ...",
    first: "VLAN dinámica",
    second: "VLAN estática",
    third: "VLAN física",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item25: {
    id: "25",
    title: "Existen diversos tipos de VLAN pero aquella que exige características especiales de retardo y ancho de banda garantizado es:",
    first: "VLAN de datos",
    second: "VLAN de voz",
    third: "VLAN nativa",
    fourth: "VLAN predeterminada",
    answer: 2,
  },
  item26: {
    id: "26",
    title: "El rango normal de VLAN es",
    first: "1 a 255",
    second: "1 a 1002",
    third: "1 a 4094",
    fourth: "Ninguna de las anteriores",
    answer: 4,
  },
  item27: {
    id: "27",
    title: "La extensión de múltiples puntos de acceso como una sóla WLAN se denomina:",
    first: "ESS",
    second: "BSS",
    third: "FSS",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item28: {
    id: "28",
    title: "La creación de subinterfaces permite el enrutamiento entre VLAN denominado:",
    first: "Enrutamiento por subinterfaz",
    second: "Subnetting",
    third: "Enrutamiento entre VLAN del router on-a-stick",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item29: {
    id: "29",
    title: "En el enrutamiento entre VLAN definido como tradicional necesitaremos tantos interfaces en el Router como ...",
    first: "VLAN definidas en la red local",
    second: "Un sólo interfaz conectado a el switch",
    third: "direcciones IP tengamos utilizadas en todos los dispositivos de red",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item30: {
    id: "30",
    title: "El protocolo de Cisco que permite mantener una instancia de STP para cada VLAN configurada en la red, se denomina:",
    first: "STP",
    second: "TCP",
    third: "VTP",
    fourth: "PVST",
    answer: 4,
  },
  item31: {
    id: "31",
    title: "En los pasos de convergencia STP, indica cual es el primer paso a realizar:",
    first: "Elegir un puente raiz",
    second: "Elegir los puertos raiz",
    third: "Elegir los puertos designados y no designados",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item32: {
    id: "32",
    title: "La capacidad principal y diferenciadora de un switch de capa 3 es la de....",
    first: "Dividir los dominios de colisión",
    second: "Enrutar paquetes entre diferentes VLAN.",
    third: "Distinguir la VLAN a la que pertenece cada paquete recibido en sus enlaces troncales",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
  item33: {
    id: "33",
    title: "Todos los puertos de un switch se convierten en miembros de la VLAN______ después del arranque inicial",
    first: "Nativa",
    second: "Predeterminada",
    third: "De datos",
    fourth: "De usuario",
    answer: 2,
  },
  item34: {
    id: "34",
    title: "Dentro de los pasos recomendados en la configuración de un cliente VTP, indique cual de los siguientes no es un paso de configuración de un cliente",
    first: "Configurar las VLAN y puertos troncales",
    second: "Configurar enlaces troncales",
    third: "Configurar puertos de acceso",
    fourth: "Todos son pasos de configuración de un cliente VTP",
    answer: 1,
  },
  item35: {
    id: "35",
    title: "Indica cual de los siguientes no es un beneficio de las VLAN",
    first: "Reducción de costos",
    second: "Seguridad",
    third: "Administración de aplicación o de proyectos más simples",
    fourth: "Mitigación de la tormenta de colisión",
    answer: 4,
  },
  item36: {
    id: "36",
    title: "Si deseamos realizar un enrutamiento entre redes con diferente VLAN, tradicionalmente necesitaremos un :",
    first: "Router",
    second: "Switch",
    third: "Hub",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
}
