const data = {
  item1: {
    id: "1",
    title: "¿Cuál de las siguientes es una actividad esencial en la función de RRHH?",
    first: "Gestión de inventarios.",
    second: "Planificación de medios para satisfacer a personas y organización",
    third: "Desarrollo de software.",
    fourth: "Mantenimiento de equipos.",
    answer: 2,
  },
  item2: {
    id: "2",
    title: "¿Cuál es el enfoque principal del subsistema de provisión de recursos humanos?",
    first: "Evaluación de desempeño.",
    second: "Reclutamiento y selección del personal.",
    third: "Desarrollo de programas de salud.",
    fourth: "Gestión de la cadena de suministro.",
    answer: 2,
  },
  item3: {
    id: "3",
    title: " ¿Qué representa el 'cuadrante 1' en el sistema de clasificación de las definiciones de la función de RRHH?",
    first: "Enfoque en planes y decisiones sobre la organización.",
    second: "Técnicas aplicadas a conseguir resultados en personas.",
    third: "Planes focalizados en los propios empleados.",
    fourth: "Aplicación de técnicas para conseguir resultados en la organización.",
    answer: 1,
  },
  item4: {
    id: "4",
    title: "¿Qué se considera esencial para el éxito de las organizaciones según la función de RRHH?",
    first: "La inversión en tecnología.",
    second: "La gestión de competencias y desarrollo de las capacidades.",
    third: "El enfoque exclusivo en la reducción de costos.",
    fourth: "La expansión rápida del mercado.",
    answer: 2,
  },
  item5: {
    id: "5",
    title: "¿Qué papel juega la evaluación de competencias y desempeño en RRHH?",
    first: "Incrementar la competencia entre empleados.",
    second: "Disminuir la motivación laboral.",
    third: "Planificar medios para satisfacer a personas y organización.",
    fourth: "Reducir los salarios y beneficios.",
    answer: 3,
  },
  item6: {
    id: "6",
    title: "¿Cómo contribuye el diseño y puesta en práctica de sistemas de retribución en RRHH?",
    first: "Reduciendo el compromiso del empleado.",
    second: "Limitando la formación y desarrollo",
    third: "Optimizando comportamientos individuales en el trabajo.",
    fourth: "Aumentando el número de conflictos laborales.",
    answer: 3,
  },
  item7: {
    id: "7",
    title: "¿Cuál es una función no asociada a RRHH?",
    first: "Gestión de la cadena de suministro.",
    second: " Planificación de recursos humanos.",
    third: " Desarrollo de la organización",
    fourth: "Remuneración y prestaciones",
    answer: 1,
  },
  item8: {
    id: "8",
    title: "¿Cuál de los siguientes no es un subsistema de RRHH?",
    first: "Provisión de recursos humanos.",
    second: "Desarrollo tecnológico.",
    third: "Mantenimiento de recursos humanos.",
    fourth: "Control de recursos humanos.",
    answer: 2,
  },
  item9: {
    id: "9",
    title: "¿Qué objetivo principal tienen las prácticas en la función de Recursos Humanos?",
    first: "Reducir costos laborales al mínimo.",
    second: "Maximizar las horas trabajadas por empleado.",
    third: "Detectar, expresar y desarrollar competencias para alcanzar objetivos organizacionales.",
    fourth: "Aumentar el control sobre las actividades de los empleados.",
    answer: 3,
  },
  item10: {
    id: "10",
    title: "Según el texto, ¿cuál es una característica esencial de las actividades de RRHH?",
    first: "Enfoque exclusivo en la compensación económica.",
    second: "Prioridad en la gestión de proyectos tecnológicos.",
    third: "Respuesta a cuestiones clave para el logro de metas organizacionales.",
    fourth: "Centralización en la gestión de infraestructuras físicas.",
    answer: 3,
  },
  item11: {
    id: "11",
    title: "¿Cuál de estas opciones NO es una tendencia actual en la función de RRHH según el texto?",
    first: "Fomento de la autonomía del empleado.",
    second: "Digitalización de procesos internos.",
    third: "Descentralización de la toma de decisiones.",
    fourth: "Reducción de la formación continua.",
    answer: 4,
  },
  item12: {
    id: "12",
    title: "¿Qué aspecto es crucial en el nuevo rol de RRHH en el contexto de digitalización?",
    first: "Reducción de la inversión en tecnología.",
    second: "Enfoque en la administración manual de tareas.",
    third: "Papel estratégico y de asesoramiento.",
    fourth: "Mantenimiento de sistemas tradicionales de gestión",
    answer: 3,
  },
  item13: {
    id: "13",
    title: "¿Qué no se considera una competencia esencial del profesional de RRHH según el texto?",
    first: "Conocimientos en dirección estratégica.",
    second: "Habilidades en programación informática avanzada.",
    third: "Capacidad para gestionar cambios",
    fourth: "Entendimiento del negocio",
    answer: 2,
  },
  item14: {
    id: "14",
    title: "En el contexto de digitalización, ¿qué se espera de RRHH respecto a los métodos digitales?",
    first: "Limitar su uso al mínimo necesario.",
    second: "Competencia y aplicación efectiva",
    third: "Focalización exclusiva en plataformas tradicionales.",
    fourth: "Preferencia por métodos administrativos manuales",
    answer: 2,
  },
  item15: {
    id: "15",
    title: "¿Qué aspecto es vital en la etapa actual de la función de RRHH según el texto?",
    first: "Regresar a prácticas administrativas tradicionales.",
    second: "Vista de RRHH como un socio estratégico.",
    third: "Disminución del enfoque en la formación continua.",
    fourth: "Reducción de la importancia de la satisfacción laboral.",
    answer: 2,
  },
  item16: {
    id: "16",
    title: "¿Cuál de las siguientes no es una actividad de RRHH centrada en las personas según el modelo propuesto?",
    first: "Planificación de los recursos humanos.",
    second: "Investigación y sistemas de información en RRHH.",
    third: "Gestión del desempeño.",
    fourth: "Planificación y gestión psicosocial de la extinción",
    answer: 4,
  },
  item17: {
    id: "17",
    title: "¿Qué enfoque se recomienda para la evaluación del rendimiento en RRHH?",
    first: "Sistemas de evaluación estándar sin adaptación.",
    second: "Uso de sistemas de evaluación personalizados.",
    third: "Evitar la evaluación para no afectar la moral.",
    fourth: "Evaluación basada únicamente en resultados financieros.",
    answer: 2,
  },
  item18: {
    id: "18",
    title: "¿Qué no se considera un objetivo del sistema de información de recursos humanos (SIRH)?",
    first: "Automatización de la toma de decisiones estratégicas.",
    second: "Apoyo a las funciones y actividades de RRHH.",
    third: "Mejora de procesos organizacionales relacionados con las personas",
    fourth: "Distribución de información relativa a las personas de la organización.",
    answer: 1,
  },
  item19: {
    id: "19",
    title: "En el modelo de gestión de talentos, ¿qué fase se relaciona con mantener a los empleados satisfechos y comprometidos?",
    first: "Adquisición",
    second: "Activación",
    third: "Beneficio",
    fourth: "Retención",
    answer: 4,
  },
  item20: {
    id: "20",
    title: "¿Cuál es el principal desafío al implementar un Sistema de Información de Recursos  Humanos (SIRH)?",
    first: "Aumentar manualmente los procesos de RRHH.",
    second: "Integración con sistemas existentes en la organización.",
    third: "Reducción del alcance funcional del departamento de RRHH.",
    fourth: "Disminución de la interacción personal entre empleados.",
    answer: 2,
  },
  item21: {
    id: "21",
    title: "¿Qué habilidad es indispensable para el profesional de RRHH en el entorno digital  actual?",
    first: "Especialización en métodos de producción industrial.",
    second: "Competencias avanzadas en programación web.",
    third: "Habilidad para analizar y utilizar grandes volúmenes de datos (Big Data).",
    fourth: "Conocimientos avanzados en criptografía.",
    answer: 3,
  },
  item22: {
    id: "22",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item23: {
    id: "23",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item24: {
    id: "24",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item25: {
    id: "25",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item26: {
    id: "26",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item27: {
    id: "27",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item28: {
    id: "28",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item29: {
    id: "29",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item30: {
    id: "30",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item31: {
    id: "31",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item32: {
    id: "32",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item33: {
    id: "33",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item34: {
    id: "34",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item35: {
    id: "35",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item36: {
    id: "36",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item37: {
    id: "37",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item38: {
    id: "38",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item39: {
    id: "39",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item40: {
    id: "40",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item41: {
    id: "41",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item42: {
    id: "42",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item43: {
    id: "43",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item44: {
    id: "44",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item45: {
    id: "45",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item46: {
    id: "46",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item47: {
    id: "47",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item48: {
    id: "48",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item49: {
    id: "49",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item50: {
    id: "50",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item51: {
    id: "51",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item52: {
    id: "52",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item53: {
    id: "53",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item54: {
    id: "54",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item55: {
    id: "55",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
  item56: {
    id: "56",
    title: "Cuál",
    first: "Aumentar.",
    second: "Integración",
    third: "Reducción",
    fourth: "Disminución",
    answer: 2,
  },
};
