const data = {
  item1: {
    id: "1",
    title: "¿Cuál de las siguientes es una actividad esencial en la función de RRHH?",
    first: "Gestión de inventarios.",
    second: "Planificación de medios para satisfacer a personas y organización",
    third: "Desarrollo de software.",
    fourth: "Mantenimiento de equipos.",
    answer: 2,
  },
  item2: {
    id: "2",
    title: "¿Cuál es el enfoque principal del subsistema de provisión de recursos humanos?",
    first: "Evaluación de desempeño.",
    second: "Reclutamiento y selección del personal.",
    third: "Desarrollo de programas de salud.",
    fourth: "Gestión de la cadena de suministro.",
    answer: 2,
  },
  item3: {
    id: "3",
    title: " ¿Qué representa el 'cuadrante 1' en el sistema de clasificación de las definiciones de la función de RRHH?",
    first: "Enfoque en planes y decisiones sobre la organización.",
    second: "Técnicas aplicadas a conseguir resultados en personas.",
    third: "Planes focalizados en los propios empleados.",
    fourth: "Aplicación de técnicas para conseguir resultados en la organización.",
    answer: 1,
  },
  item4: {
    id: "4",
    title: "¿Qué se considera esencial para el éxito de las organizaciones según la función de RRHH?",
    first: "La inversión en tecnología.",
    second: "La gestión de competencias y desarrollo de las capacidades.",
    third: "El enfoque exclusivo en la reducción de costos.",
    fourth: "La expansión rápida del mercado.",
    answer: 2,
  },
  item5: {
    id: "5",
    title: "¿Qué papel juega la evaluación de competencias y desempeño en RRHH?",
    first: "Incrementar la competencia entre empleados.",
    second: "Disminuir la motivación laboral.",
    third: "Planificar medios para satisfacer a personas y organización.",
    fourth: "Reducir los salarios y beneficios.",
    answer: 3,
  },
  item6: {
    id: "6",
    title: "¿Cómo contribuye el diseño y puesta en práctica de sistemas de retribución en RRHH?",
    first: "Reduciendo el compromiso del empleado.",
    second: "Limitando la formación y desarrollo",
    third: "Optimizando comportamientos individuales en el trabajo.",
    fourth: "Aumentando el número de conflictos laborales.",
    answer: 3,
  },
  item7: {
    id: "7",
    title: "¿Cuál es una función no asociada a RRHH?",
    first: "Gestión de la cadena de suministro.",
    second: " Planificación de recursos humanos.",
    third: " Desarrollo de la organización",
    fourth: "Remuneración y prestaciones",
    answer: 1,
  },
  item8: {
    id: "8",
    title: "¿Cuál de los siguientes no es un subsistema de RRHH?",
    first: "Provisión de recursos humanos.",
    second: "Desarrollo tecnológico.",
    third: "Mantenimiento de recursos humanos.",
    fourth: "Control de recursos humanos.",
    answer: 2,
  },
  item9: {
    id: "9",
    title: "¿Qué objetivo principal tienen las prácticas en la función de Recursos Humanos?",
    first: "Reducir costos laborales al mínimo.",
    second: "Maximizar las horas trabajadas por empleado.",
    third: "Detectar, expresar y desarrollar competencias para alcanzar objetivos organizacionales.",
    fourth: "Aumentar el control sobre las actividades de los empleados.",
    answer: 3,
  },
  item10: {
    id: "10",
    title: "Según el texto, ¿cuál es una característica esencial de las actividades de RRHH?",
    first: "Enfoque exclusivo en la compensación económica.",
    second: "Prioridad en la gestión de proyectos tecnológicos.",
    third: "Respuesta a cuestiones clave para el logro de metas organizacionales.",
    fourth: "Centralización en la gestión de infraestructuras físicas.",
    answer: 3,
  },
  item11: {
    id: "11",
    title: "¿Cuál de estas opciones NO es una tendencia actual en la función de RRHH según el texto?",
    first: "Fomento de la autonomía del empleado.",
    second: "Digitalización de procesos internos.",
    third: "Descentralización de la toma de decisiones.",
    fourth: "Reducción de la formación continua.",
    answer: 4,
  },
  item12: {
    id: "12",
    title: "¿Qué aspecto es crucial en el nuevo rol de RRHH en el contexto de digitalización?",
    first: "Reducción de la inversión en tecnología.",
    second: "Enfoque en la administración manual de tareas.",
    third: "Papel estratégico y de asesoramiento.",
    fourth: "Mantenimiento de sistemas tradicionales de gestión",
    answer: 3,
  },
  item13: {
    id: "13",
    title: "¿Qué no se considera una competencia esencial del profesional de RRHH según el texto?",
    first: "Conocimientos en dirección estratégica.",
    second: "Habilidades en programación informática avanzada.",
    third: "Capacidad para gestionar cambios",
    fourth: "Entendimiento del negocio",
    answer: 2,
  },
  item14: {
    id: "14",
    title: "En el contexto de digitalización, ¿qué se espera de RRHH respecto a los métodos digitales?",
    first: "Limitar su uso al mínimo necesario.",
    second: "Competencia y aplicación efectiva",
    third: "Focalización exclusiva en plataformas tradicionales.",
    fourth: "Preferencia por métodos administrativos manuales",
    answer: 2,
  },
  item15: {
    id: "15",
    title: "¿Qué aspecto es vital en la etapa actual de la función de RRHH según el texto?",
    first: "Regresar a prácticas administrativas tradicionales.",
    second: "Vista de RRHH como un socio estratégico.",
    third: "Disminución del enfoque en la formación continua.",
    fourth: "Reducción de la importancia de la satisfacción laboral.",
    answer: 2,
  },
  item16: {
    id: "16",
    title: "¿Cuál de las siguientes no es una actividad de RRHH centrada en las personas según el modelo propuesto?",
    first: "Planificación de los recursos humanos.",
    second: "Investigación y sistemas de información en RRHH.",
    third: "Gestión del desempeño.",
    fourth: "Planificación y gestión psicosocial de la extinción",
    answer: 4,
  },
  item17: {
    id: "17",
    title: "¿Qué enfoque se recomienda para la evaluación del rendimiento en RRHH?",
    first: "Sistemas de evaluación estándar sin adaptación.",
    second: "Uso de sistemas de evaluación personalizados.",
    third: "Evitar la evaluación para no afectar la moral.",
    fourth: "Evaluación basada únicamente en resultados financieros.",
    answer: 2,
  },
  item18: {
    id: "18",
    title: "¿Qué no se considera un objetivo del sistema de información de recursos humanos (SIRH)?",
    first: "Automatización de la toma de decisiones estratégicas.",
    second: "Apoyo a las funciones y actividades de RRHH.",
    third: "Mejora de procesos organizacionales relacionados con las personas",
    fourth: "Distribución de información relativa a las personas de la organización.",
    answer: 1,
  },
  item19: {
    id: "19",
    title: "En el modelo de gestión de talentos, ¿qué fase se relaciona con mantener a los empleados satisfechos y comprometidos?",
    first: "Adquisición",
    second: "Activación",
    third: "Beneficio",
    fourth: "Retención",
    answer: 4,
  },
  item20: {
    id: "20",
    title: "¿Cuál es el principal desafío al implementar un Sistema de Información de Recursos  Humanos (SIRH)?",
    first: "Aumentar manualmente los procesos de RRHH.",
    second: "Integración con sistemas existentes en la organización.",
    third: "Reducción del alcance funcional del departamento de RRHH.",
    fourth: "Disminución de la interacción personal entre empleados.",
    answer: 2,
  },
  item21: {
    id: "21",
    title: "¿Qué habilidad es indispensable para el profesional de RRHH en el entorno digital  actual?",
    first: "Especialización en métodos de producción industrial.",
    second: "Competencias avanzadas en programación web.",
    third: "Habilidad para analizar y utilizar grandes volúmenes de datos (Big Data).",
    fourth: "Conocimientos avanzados en criptografía.",
    answer: 3,
  },
  item22: {
    id: "22",
    title: " ¿Qué aspecto NO es considerado un beneficio directo de la digitalización en RRHH?",
    first: "Mejora de la experiencia del empleado.",
    second: " Incremento en el uso de papel y procesos manuales.",
    third: "Eficiencia en la gestión del talento",
    fourth: "Uso efectivo de plataformas para la comunicación y trabajo en equipo",
    answer: 2,
  },
  item23: {
    id: 23,
    title: "En relación con la gestión del desempeño, ¿qué se considera más beneficioso?",
    first: "Sistemas de evaluación que promuevan la participación de los empleados.",
    second: "Integración",
    third: "Uso exclusivo de evaluaciones top-down",
    fourth: "Eliminación de toda forma de evaluación de desempeño",
    answer: 2,
  },
  item24: {
    id: 24,
    title: "¿Qué no se espera de la función de RRHH en la fase de retención del modelo de gestión de talentos?",
    first: "Implementación de políticas rígidas de permanencia.",
    second: "Desarrollo de un ambiente laboral satisfactorio.",
    third: "Oferta de compensaciones y beneficios competitivos.",
    fourth: "Fomento de la formación continua y el desarrollo profesional.",
    answer: 1,
  },
  item25: {
    id: 25,
    title: "¿Cuál de las siguientes NO es una predicción sobre el futuro de la función de RRHH?",
    first: "Disminución del enfoque en las métricas y análisis de datos.",
    second: "Mayor demanda para medir y evaluar el valor de las iniciativas de capital humano.",
    third: "Transición hacia un enfoque más centrado en la ciencia de las decisiones.",
    fourth: "Aumento en el uso de tecnología para mejorar procesos de selección.",
    answer: 1,
  },
  item26: {
    id: 26,
    title: "¿Qué enfoque de gestión de RRHH se considera obsoleto según las tendencias actuales?",
    first: "Orientación hacia el desarrollo del talento y la participación de los empleados.",
    second: "Enfoque administrativo centrado en tareas y procedimientos burocráticos.",
    third: "Adopción de tecnologías digitales para la optimización de procesos.",
    fourth: "Implementación de prácticas basadas en la Gestión de la Calidad Total.",
    answer: 2,
  },
  item27: {
    id: 27,
    title: "¿Qué es la Gestión del Talento (GT)?",
    first: "La reducción de costos a través de la automatización de procesos.",
    second: "El proceso de contratar, socializar, desarrollar y retener empleados mientras se atrae a individuos altamente cualificados.",
    third: "Un sistema de gestión utilizado únicamente para la nómina y beneficios.",
    fourth: "Estrategias para aumentar el número de empleados en la organización.",
    answer: 2,
  },
  item28: {
    id: 28,
    title: "¿Qué propone el texto para mejorar la operacionalización del concepto de talento?",
    first: "Ignorar las definiciones existentes y crear una nueva industria.",
    second: "Utilizar únicamente definiciones basadas en la experiencia práctica.",
    third: "Disponer de una definición operativa unificada del concepto de talento.",
    fourth: "Limitar la gestión del talento a la evaluación de desempeño.",
    answer: 3,
  },
  item29: {
    id: 29,
    title: "¿Cuál es la principal razón por la cual las aplicaciones de software de Gestión del Talento se están adoptando globalmente?",
    first: "Bajo costo.",
    second: "Facilidad de uso.",
    third: "Requisitos legislativos de bajo impacto.",
    fourth: "Preferencia por soluciones locales.",
    answer: 2,
  },
  item30: {
    id: 30,
    title: "¿Qué define principalmente a la gestión del talento dentro de una organización?",
    first: "La administración exclusiva de los salarios de los empleados.",
    second: "La contratación de personal basada únicamente en sus habilidades técnicas.",
    third: "La identificación, desarrollo, y retención de individuos con potencial clave para el éxito de la organización.",
    fourth: "La gestión de los recursos materiales y financieros de la empresa.",
    answer: 3,
  },
  item31: {
    id: 31,
    title: "¿Cuál es el primer paso en un proceso efectivo de gestión del talento?",
    first: "Desarrollo de programas de capacitación.",
    second: "Identificación de los talentos dentro y fuera de la organización.",
    third: "Implementación de sistemas de recompensas.",
    fourth: "Evaluación del desempeño de los empleados.",
    answer: 2,
  },
  item32: {
    id: 32,
    title: "¿Qué NO se considera un objetivo de la gestión del talento?",
    first: "Aumento de la competitividad de la organización.",
    second: "Reducción de los costos operativos mediante la disminución de salarios.",
    third: "Retención de empleados altamente calificados.",
    fourth: "Fomento de un ambiente laboral que promueva el desarrollo profesional.",
    answer: 2,
  },
  item33: {
    id: 33,
    title: "¿Qué característica NO se asocia con un sistema efectivo de gestión del talento?",
    first: "Enfoque únicamente en el desempeño a corto plazo.",
    second: "Integración de los objetivos de talento con la estrategia de la empresa.",
    third: "Desarrollo de una cultura organizacional que valora el aprendizaje.",
    fourth: "Identificación proactiva de necesidades futuras de habilidades.",
    answer: 1,
  },
  item34: {
    id: 34,
    title: "¿Qué beneficio aporta una gestión del talento orientada hacia el desarrollo de liderazgo?",
    first: "Disminución del número de líderes dentro de la organización.",
    second: "Asegura una reserva de líderes capaces de asumir roles críticos.",
    third: "Centraliza la toma de decisiones en la alta gerencia.",
    fourth: "Limita el liderazgo a un conjunto predefinido de características.",
    answer: 2,
  },
  item35: {
    id: 35,
    title: "¿Cómo impacta positivamente la gestión del talento en la innovación de la empresa?",
    first: "Incrementando la resistencia al cambio.",
    second: "Promoviendo una cultura de conformismo.",
    third: "Facilitando la incorporación de nuevas ideas y enfoques.",
    fourth: "Reduciendo la diversidad de pensamiento.",
    answer: 3,
  },
  item36: {
    id: 36,
    title: "¿Qué estrategia es efectiva para retener el talento en la organización?",
    first: "Implementación de políticas rígidas de trabajo.",
    second: "Desarrollo de planes de carrera y oportunidades de crecimiento.",
    third: "Limitación de la formación profesional continua.",
    fourth: "Aumento del trabajo en solitario y aislamiento de equipos.",
    answer: 2,
  },
  item37: {
    id: 37,
    title: "¿Cuál es una tendencia actual en la gestión del talento?",
    first: "Regreso a métodos tradicionales de gestión de personal.",
    second: "Uso de tecnologías digitales para mejorar el reclutamiento y la capacitación.",
    third: "Disminución de la importancia de la cultura organizacional.",
    fourth: "Enfoque exclusivo en la eficiencia operativa sin considerar el desarrollo del empleado.",
    answer: 2,
  },
  item38: {
    id: 38,
    title: "¿Qué es la gestión del talento?",
    first: "Proceso de aumentar los salarios de los empleados más antiguos.",
    second: "Estrategia para reducir el tamaño de la fuerza laboral.",
    third: "Método para identificar y desarrollar habilidades específicas en empleados seleccionados.",
    fourth: "Conjunto de prácticas enfocadas en atraer, desarrollar, retener y utilizar a las personas con habilidades y competencias necesarias.",
    answer: 4,
  },
  item39: {
    id: 39,
    title: "¿Cuál es una estrategia clave para retener talento en una organización?",
    first: "Implementación de un sistema de trabajo remoto para todos los empleados.",
    second: "Creación de planes de desarrollo personalizados y oportunidades de carrera.",
    third: "Reducción de los beneficios laborales para aumentar la competitividad.",
    fourth: "Centralización de las decisiones de gestión del talento en el departamento de RRHH.",
    answer: 2,
  },
  item40: {
    id: 40,
    title: "¿Qué papel juega la tecnología en la gestión moderna del talento?",
    first: "Ninguno, ya que las relaciones humanas no pueden ser gestionadas por tecnología.",
    second: "Facilitar la automatización de todas las decisiones de RRHH.",
    third: "Soportar procesos de gestión del talento mediante sistemas de información y herramientas de análisis.",
    fourth: "Reemplazar completamente la necesidad de interacciones personales en la gestión de RRHH.",
    answer: 3,
  },
  item41: {
    id: 41,
    title: "¿Cómo contribuye una efectiva gestión del talento al éxito de una organización?",
    first: "Incrementando la cantidad de empleados.",
    second: "Reduciendo los costos laborales al mínimo posible.",
    third: "Asegurando que las personas adecuadas estén en los roles adecuados, impulsando el desempeño organizacional.",
    fourth: "Limitando el desarrollo profesional a unos pocos empleados seleccionados.",
    answer: 3,
  },
  item42: {
    id: 42,
    title: "En la gestión del talento, ¿qué significa mapear el talento?",
    first: "Despedir a empleados que no cumplen con las expectativas.",
    second: "Identificar y documentar las habilidades y potencial de los empleados.",
    third: "Seguir el movimiento de los talentos entre competidores.",
    fourth: "Limitar el desarrollo de talentos a las necesidades actuales de la empresa.",
    answer: 2,
  },
  item43: {
    id: 43,
    title: "¿Qué es la gestión del talento según el texto?",
    first: "Un proceso exclusivamente centrado en la contratación de personal.",
    second: "La administración de nóminas y beneficios para empleados destacados.",
    third: "El desarrollo, retención y atracción de los empleados más valiosos.",
    fourth: "La evaluación anual del desempeño de los empleados.",
    answer: 3,
  },
  item44: {
    id: 44,
    title: "¿Cuál de las siguientes NO es una fase en el modelo de gestión de talentos mencionado?",
    first: "Adquisición.",
    second: "Activación.",
    third: "Exclusión.",
    fourth: "Retención.",
    answer: 3,
  },
  item45: {
    id: 45,
    title: "¿Qué estrategia de gestión del talento se enfoca en la adaptación del empleado a la cultura de la empresa?",
    first: "Capacitación técnica intensiva.",
    second: "Socialización y orientación.",
    third: "Políticas de trabajo remoto.",
    fourth: "Bonificaciones basadas en resultados.",
    answer: 2,
  },
  item46: {
    id: 46,
    title: "¿Qué herramienta se sugiere utilizar para mejorar el proceso de selección en la gestión del talento?",
    first: "Encuestas de satisfacción de empleados.",
    second: "Análisis de competencia entre empleados.",
    third: "Tecnología de análisis de datos y people analytics.",
    fourth: "Reuniones presenciales exclusivas.",
    answer: 3,
  },
  item47: {
    id: 47,
    title: "¿Cuál es el principal objetivo de la retención de talentos?",
    first: "Reducir costos operativos.",
    second: "Aumentar la competencia interna.",
    third: "Mantener a los empleados valiosos motivados y comprometidos.",
    fourth: "Establecer un sistema de jerarquía más claro.",
    answer: 3,
  },
  item48: {
    id: 48,
    title: "¿Qué aspecto NO se considera clave en la creación de un entorno de trabajo que fomente la retención del talento?",
    first: "Espacios de trabajo abiertos y compartidos.",
    second: "Oportunidades de desarrollo profesional continuo.",
    third: "Políticas rígidas de asistencia y horario.",
    fourth: "Reconocimiento y recompensa del desempeño.",
    answer: 3,
  },
  item49: {
    id: 49,
    title: "En el contexto de gestión del talento, ¿cómo se define talento?",
    first: "Únicamente las habilidades técnicas de un empleado.",
    second: "La combinación de habilidades, conocimientos y potencial de crecimiento",
    third: "Experiencia laboral previa en empresas de renombre.",
    fourth: "La capacidad para trabajar largas horas.",
    answer: 2,
  },
  item50: {
    id: 50,
    title: "¿Qué se considera un beneficio directo de una efectiva gestión del talento?",
    first: "Disminución de la innovación.",
    second: "Incremento en la satisfacción y lealtad del cliente.",
    third: "Aumento en la rotación de personal.",
    fourth: "Reducción de oportunidades de formación.",
    answer: 2,
  },
  item51: {
    id: 51,
    title: "¿Qué método NO es efectivo para el desarrollo del talento?",
    first: "Programas de mentoría.",
    second: "Planes de sucesión y carrera.",
    third: "Evaluaciones de desempeño sin seguimiento.",
    fourth: "Capacitación y formación continua.",
    answer: 3,
  },
  item52: {
    id: 52,
    title: "¿Qué rol juegan las plataformas de e-learning en la gestión del talento?",
    first: "Reducir el interés en la formación continua.",
    second: "Facilitar el acceso a formación y desarrollo profesional.",
    third: "Limitar las oportunidades de aprendizaje a roles específicos.",
    fourth: "Aumentar la dependencia de formación presencial.",
    answer: 2,
  },
  item53: {
    id: 53,
    title: "¿Cómo impacta una estrategia de gestión del talento en la innovación dentro de la empresa?",
    first: "Disminuye la capacidad de innovación al estandarizar procesos.",
    second: "Aumenta la innovación al fomentar la diversidad de habilidades y conocimientos.",
    third: "No tiene impacto alguno en la innovación.",
    fourth: "Restringe la innovación a departamentos de I+D exclusivamente.",
    answer: 2,
  },
  item54: {
    id: 54,
    title: "¿Cuál es un indicador clave del éxito en la gestión del talento?",
    first: "Número de empleados en la empresa.",
    second: "Total de horas trabajadas por empleado.",
    third: "Nivel de compromiso y satisfacción del empleado.",
    fourth: "Cantidad de políticas de RRHH implementadas.",
    answer: 3,
  },
  item55: {
    id: 55,
    title: "¿Cuál de las siguientes NO es una práctica recomendada en la retención de talentos?",
    first: "Ofrecer un ambiente de trabajo flexible y dinámico.",
    second: "Ignorar las expectativas y necesidades personales de los empleados.",
    third: "Promover oportunidades de crecimiento y desarrollo.",
    fourth: "Reconocer y recompensar el desempeño y logros.",
    answer: 2,
  },
  item56: {
    id: 56,
    title: "¿Qué estrategia es menos efectiva para fomentar la innovación a través de la gestión del talento?",
    first: "Establecer equipos multidisciplinarios.",
    second: "Promover la competencia interna como único motivador.",
    third: "Incentivar la experimentación y el aprendizaje de errores.",
    fourth: "Crear espacios para el intercambio de ideas y colaboración.",
    answer: 2,
  },
};
