const data = {
  item37: {
    id: "37",
    title: "Si deseamos crear un dominio DNS de tipo alias, lo haremos mediante un registro de tipo",
    first: "A",
    second: "MX",
    third: "CNAME",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item38: {
    id: "38",
    title: "En una red conmutada sin existencia de VLAN's...",
    first: "Tenemos un único dominio de difusión",
    second: "Tenemos un único dominio de colisión y múltiples dominios de difusión",
    third: "Tenemos varios dominios de colisión y difusión",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item40: {
    id: "40",
    title: "Si queremos configurar una identidad IP al switch, deberemos configurarle un",
    first: "SVI",
    second: "PCI",
    third: "IPS",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item41: {
    id: "41",
    title: "El ID por defecto en un switch de la VLAN nativa es:",
    first: "1",
    second: "99",
    third: "1002",
    fourth: "Ninguna de las Anteriores",
    answer: 1,
  },
item42: {
    id: "42",
    title: "En el prototocolo de autenticación extensible (EAP) se hace uso de un servidor de autenticación:",
    first: "DNS",
    second: "DHCP",
    third: "RADIUS",
    fourth: "Ninguna de las Anteriores",
    answer: 3,
  },
item43: {
    id: "43",
    title: "Indique cual de las siguientes medidas es la más efectiva para proteger una LAN inalámbrica",
    first: "Camuflaje SSID",
    second: "Filtrado de direcciones MAC",
    third: "Seguridad WLAN - WPA o WPA2",
    fourth: "Todas son igualmente efectivas",
    answer: 3,
  },
item44: {
    id: "44",
    title: "La denegación de servicio es un ataque que puede ser evitado con el estándar:",
    first: "802.11a",
    second: "802.11n",
    third: "802.11g",
    fourth: "Ninguna de las anteriores",
    answer: 4,
  },
item45: {
    id: "45",
    title: "Los puntos de acceso de una red WLAN deben situarse:",
    first: "En cuartos inaccesibles",
    second: "Cerca del techo en el centro de cada area de cobertura",
    third: "En las paredes para evitar refacciones",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item46: {
    id: "46",
    title: "Indica cual de las siguientes propiedades no emite un punto de acceso en sus beacons:",
    first: "SSID",
    second: "Velocidades admitidas",
    third: "Implementación de seguridad",
    fourth: "Solicitud de conexión",
    answer: 4,
  },
item47: {
    id: "47",
    title: "Las redes inalámbricas que operan sin necesidad de puntos de acceso se denomina:",
    first: "Sin infraestructura",
    second: "Ad-hoc",
    third: "Hand-over",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item48: {
    id: "48",
    title: "En la banda de 2.4GHZ, la portadora de cada canal tiene una distancia al siguiente canal de",
    first: "5MHz",
    second: "10MHz",
    third: "25MHz",
    fourth: "50MHz",
    answer: 1,
  },
item49: {
    id: "49",
    title: "Indica cual de los siguientes estándares de Wifi permite la transferencia hasta 54Mbps y opera en la banda de 2.4GHz",
    first: "802.11a",
    second: "802.11b",
    third: "802.11g",
    fourth: "802.11n",
    answer: 3,
  },
item50: {
    id: "50",
    title: "Indique cual de las siguientes no es una característica de la definición de robustez",
    first: "Sencillez",
    second: "Escalabilidad",
    third: "Eficiencia",
    fourth: "Todas son características deseables en una red robusta",
    answer: 4,
  },
item51: {
    id: "51",
    title: "En el diseño de una red, cuando una de las premisas a cumplir es la menor latencia, se recomienda implementar una red:",
    first: "Enrutada",
    second: "Conmutada",
    third: "Segmentada",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item52: {
    id: "52",
    title: "A veces el diseño elegido en una red no viene condicionado por requerimientos no objetivos denominados",
    first: "Requerimientos de Coste",
    second: "Requerimientos Políticos y Filosóficos",
    third: "Requerimientos de Seguridad",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item53: {
    id: "53",
    title: "Respecto a la evaluación del ancho de banda necesario en una red,seleccione la afirmación errónea",
    first: "Es sencillo evaluarlo de forma previa",
    second: "Deberemos recopilar la mayor información de perfiles y volúmen de tráfico",
    third: "Es importante identificar los flujos de datos",
    fourth: "Se debe tener en cuenta la progresión de la institución donde se vaya a instalar dicha red",
    answer: 1,
  },
item54: {
    id: "54",
    title: "Seleccione la afirmación correcta",
    first: "Si el dinero gastado en construir la red es menos que el ahorro tal vez no sea necesaria",
    second: "Gracias a la tecnología de la nube, la localización de los recursos es independiente del diseño de la red",
    third: "La instalación actual de una red debe ser tenida en cuenta en el diseño de una nueva red",
    fourth: "La solución propuesta en un diseño de red debe siempre ofrecer los últimos avances tecnológicos",
    answer: 3,
  },
item55: {
    id: "55",
    title: "Indique cual de los siguientes no se trataría de un requerimiento o característica a tener en cuenta en el diseño inicial de una red.",
    first: "Coste",
    second: "Ancho de Banda",
    third: "Localización",
    fourth: "Sistemas operativos",
    answer: 4,
  },
item56: {
    id: "56",
    title: "Indica una característica errónea de la tolerancia a fallos mediante balanceo",
    first: "El equipo de backup está activo normalmente",
    second: "No existe realmente primario y Backup",
    third: "Cada elemento debe ser capaz de soportar toda la carga",
    fourth: "Disminuye la capacidad de la red",
    answer: 4,
  },
item57: {
    id: "57",
    title: "Ante la recuperación automática ante fallos, indica la afirmación errónea:",
    first: "En la recuperación externa son los elementos soft quienes gestionan la recuperación",
    second: "En la recuperación intrínseca son los propios elementos soft o hard quienes gestionan la recuperación",
    third: "La recuperación externa implica un punto adicional y único de fallos",
    fourth: "En la recuperación externa, un mal diagnostico del elemento provoca malas acciones",
    answer: 1,
  },
item58: {
    id: "58",
    title: "Indique la afirmación errónea",
    first: "A mayor redundancia , mayor complejidad",
    second: "El rendimiento siempre se mejora con elementos redundantes",
    third: " La complejidad en administración puede ser contraproducente",
    fourth: "Las redundancias pueden crecer exponencialmente en dispositivos de acceso",
    answer: 2,
  },
item59: {
    id: "59",
    title: "Respecto a la redundancia en las redes indique la afirmación errónea",
    first: "La duplicidad de los elementos soluciona todos los problemas",
    second: "La redundancia ayuda en tareas de mantenimiento",
    third: "El rendimiento se mejora sólo si se permite la carga compartida de trabajo.",
    fourth: "Es recomendable duplicar los elementos clave en la red para garantizar la fiabilidad",
    answer: 1,
  },
};
