const data = {
  item1: {
    id: "1",
    title: "¿Cuál es el propósito principal de un plan de pruebas en pruebas de usabilidad?",
    first: "Establecer solamente los criterios técnicos del producto",
    second:
      "Utilizarse únicamente en las etapas finales del desarrollo",
    third:
      "Guiar la metodología, participantes y objetivos, adaptándose con la retroalimentación",
    fourth:
      "Evitar la planificación detallada para mayor flexibilidad en las pruebas",
    answer: 3,
  },
  item2: {
    id: "2",
    title: "¿Cuál es un aspecto clave del plan de pruebas en pruebas de usabilidad?",
    first:
      "Enfocarse únicamente en la parte técnica del producto",
    second:
      "Realizar las pruebas solo en las etapas finales de desarrollo",
    third: "Limitar las pruebas a usuarios experimentados para obtener resultados rápidos",
    fourth:
      "Incluir secciones detalladas y alinearse con objetivos comerciales y necesidades del producto",
    answer: 4,
  },
  item3: {
    id: "3",
    title: "¿Cuál es una práctica importante en el diseño de pruebas de usabilidad?",
    first:
      "Adaptar el diseño de la prueba a los objetivos específicos y alternar el orden de las tareas para evitar sesgos",
    second:
      "Usar siempre el mismo grupo de participantes para todas las pruebas",
    third:
      "Evitar el análisis estadístico en el diseño de la prueba para simplificar el proceso",
    fourth:
      "Realizar pruebas solo con usuarios experimentados para obtener resultados más rápidos",
    answer: 1,
  },
  item4: {
    id: "4",
    title: "Durante la realización de una prueba con observadores. ¿Qué es lo que debe hacer el moderador antes de comenzar la prueba?",
    first:
      "Nada",
    second:
      "Comunicar todo lo que se realizará en la prueba",
    third:
      "Decir a cada observador donde debe colocarse",
    fourth:
      "En las pruebas de usabilidad nunca hay observadores",
    answer: 2,
  },
  item5: {
    id: "5",
    title: "¿Cuales son las formas de priorizar tareas?",
    first:
      "Prioridad por frecuencia, gravedad, disposicion y vulnerabilidad ",
    second:
      "Prioridad por criticidad, vulnerabilidad y frecuencia",
    third:
      "Prioridad por severidad, vulnerabilidad y frecuencia",
    fourth:
      "Normalmente se prioriza en funcion del tiempo que se tarda en realizar dicha tarea",
    answer: 1,
  },
  item6: {
    id: "6",
    title: "¿Cuál de los siguientes es un criterio de éxito para una tarea en una prueba de usabilidad?",
    first:
      "La tasa de error de los participantes",
    second:
      "El tiempo que tarda un participante en completar la tarea",
    third:
      "La satisfacción de los participantes con la tarea",
    fourth:
      "La opinión del moderador sobre la facilidad de uso de la tarea",
    answer: 1,
  },
  item7: {
    id: "7",
    title: "Los acuerdos de no divulgación o confidencialidad (NDA o CDA) son",
    first:
      "Acuerdos legalmente vinculantes que protegen la propiedad intelectual de su empresa",
    second:
      "Normas establecidas por el gobierno, y todos deben cumplirlas, independientemente de dónde trabajen",
    third:
      "Acuerdos de tus obligaciones éticas hacia el participante",
    fourth:
      "Establecidas por las empresas, a menudo con el objetivo de asegurar que los empleados no infrinjan las leyes o para imponer buenas prácticas comerciales",
    answer: 1,
  },
  item8: {
    id: "8",
    title: "¿Cuál no forma parte de las consideraciones éticas?",
    first:
      "No hacer daño",
    second:
      "El derecho a ser informado",
    third:
      "Lenguaje apropiado ",
    fourth:
      "Lenguaje inclusivo",
    answer: 4,
  },
  item9: {
    id: "9",
    title: "¿Qué afirmación es incorrecta?",
    first:
      "Los participantes deben sentirse libres de retirarse de tu actividad sin penalización en cualquier momento del estudio",
    second:
      "Se debe evitar ofrecer incentivos excesivos o inapropiados para atraer a los participantes, ya que pueden coaccionarlos.",
    third:
      "No es necesario informar a los participantes de los riesgos al principio del estudio ",
    fourth: "Debes proporcionar servicios, hacer recomendaciones y realizar investigaciones solo dentro de los límites de tus competencias.",
    answer: 3,
  },
  item10: {
    id: "10",
    title: "¿Cuál de las siguientes afirmaciones es correcta respecto a los tests de usabilidad?",
    first:
      "Los tests de campo son más eficientes en términos de tiempo y recursos que los tests en laboratorio",
    second:
      "Los tests en laboratorio no permiten obtener datos cuantitativos.",
    third:
      "Se aconseja realizar un test en laboratorio antes de los tests de campo para poder descartar el máximo número de problemas y obtener datos cuantitativos sólidos",
    fourth:
      "Los tests de campo no permiten obtener datos cualitativos.",
    answer: 3,
  },
  item11: {
    id: "11",
    title: "¿Cuál de las siguientes afirmaciones es correcta respecto a las pruebas de usabilidad en las instalaciones de un usuario?",
    first:
      "No es necesario obtener el permiso de la dirección y del participante para realizar pruebas de usabilidad en el lugar de trabajo del usuario",
    second:
      "Durante la sesión de pruebas, no es necesario llevar guiones de ayuda para llevar a cabo la evaluación",
    third:
      "Realizar pruebas en múltiples ubicaciones geográficas no requiere una inversión adicional.",
    fourth:
      "El 20% de los problemas de usabilidad pueden ser específicos del lugar o del contexto",
    answer: 4,
  },
  item12: {
    id: "12",
    title: "¿Cuál de las siguientes afirmaciones es correcta respecto a los tests de usabilidad realizados en laboratorios equipados?",
    first:
      "No es necesario separar la sala de observación y la sala de pruebas con un cristal con visibilidad en un único sentido",
    second:
      "El equipamiento básico para la sala de prueba no necesita incluir una cámara y un micrófono para grabar los comentarios del usuario",
    third: "No es necesario un programa específico para registrar y monitorizar la interacción del usuario en la sala de observación",
    fourth:
      "Uno de los programas más comunes para la realización de tests con usuarios es el Morae",
    answer: 4,
  },
  item13: {
    id: "13",
    title:
      "Si durante las pruebas ocurriera un problema el …. podria solventar la situación",
    first: "Experto",
    second: "Cronometrador",
    third: "Observador",
    fourth: "Moderador",
    answer: 1,
  },
  item14: {
    id: "14",
    title: "¿Cuál no es una ventaja del entorno de prueba individual modificado?",
    first:
      "Libertad de movimiento para el moderador",
    second: "El moderador no se preocupa por su lenguaje corporal",
    third: "El participante puede expresar sus pensamientos en voz alta",
    fourth:
      "El moderador esta próximo al participante",
    answer: 4,
  },
  item15: {
    id: "15",
    title: "¿En que configuración de entorno de prueba el participante se encuentra solo?",
    first: "Individual grande",
    second: "Sala de observación electrónica",
    third: "Configuración clasica laboratorio de pruebas",
    fourth: "Habitación individual",
    answer: 3,
  },
  item16: {
    id: "16",
    title: "¿Cuál es uno de los propósitos del cuestionario de antecedentes?",
    first: "Evaluar la calidad de los materiales de evaluación",
    second: "Proporcionar información histórica de los participantes.",
    third: "Orientar a los participantes en la sesión de evaluación",
    fourth: "Desarrollar pautas para observadores",
    answer: 2,
  },
  item17: {
    id: "17",
    title: "¿Cuál es uno de los elementos que se sugiere incluir en el guión de orientación según el texto?",
    first: "Lista de instrucciones para observadores",
    second: "Cuestionario de antecedentes",
    third: "Explicación del 'layout' de la prueba",
    fourth: "Acuerdo de confidencialidad",
    answer: 3,
  },
  item18: {
    id: "18",
    title: "¿Por qué es recomendable realizar una prueba del cuestionario con alguien que encaje en el perfil de usuario?",
    first: "Para evaluar la calidad del cuestionario",
    second: "Para obtener participantes adecuados",
    third: "Para orientar a los participantes",
    fourth: "Para optimizar el tiempo de respuesta",
    answer: 2,
  },
  item19: {
    id: "19",
    title: "¿Cuál es el propósito de las herramientas de recopilación de datos en las pruebas de usabilidad?",
    first: "Reducir la cantidad de participantes",
    second: "Aumentar la complejidad de la prueba",
    third: "Facilitar el análisis y la presentación de informes",
    fourth: "Ignorar la relevancia de los datos",
    answer: 3,
  },
  item20: {
    id: "20",
    title: "¿Qué tipo de datos caen en la categoría de datos de preferencia en las pruebas de usabilidad?",
    first: "Medidas objetivas de comportamiento",
    second: "Tasas de error y recuentos de elementos",
    third: "Opiniones subjetivas y sentimientos del participante",
    fourth: "Información cuantitativa y cualitativa",
    answer: 3,
  },
  item21: {
    id: "21",
    title: "¿Qué forma de recopilación de datos es útil para organizaciones con pocos recursos internos?",
    first: "Recolección de datos automatizados",
    second: "Recopilación de datos en línea",
    third: "Recopilación de datos generada por el usuario",
    fourth: "Recopilación manual de datos",
    answer: 3,
  },
  item22: {
    id: "22",
    title: "¿Cuál es una ventaja de leer los escenarios a los participantes, especialmente si son complejos?",
    first: "Incrementa la confusión",
    second: "Permite una interacción efectiva y asegura la comprensión",
    third: "Ralentiza el ritmo de la prueba",
    fourth: "Limita la participación de los usuarios",
    answer: 2,
  },
  item23: {
    id: "23",
    title: "¿Por qué es importante secuenciar los escenarios de tareas en el orden probable de ejecución?",
    first: "Solo por conveniencia",
    second: "Preserva la ilusión de autenticidad y guía a los participantes de manera natural",
    third: "No tiene impacto en la prueba",
    fourth: "Facilita la lectura por parte de los participantes",
    answer: 2,
  },
  item24: {
    id: "24",
    title: "¿Cuándo podría ser adecuado permitir que los participantes lean los escenarios por sí mismos?",
    first: "En pruebas altamente interactivas",
    second: "Durante pruebas exploratorias tempranas",
    third: "Si se quiere una interacción efectiva",
    fourth: "Para minimizar el contacto en pruebas de validación",
    answer: 1,
  },
  item25: {
    id: "25",
    title: "¿Qué cualidades debe tener el cuestionario posterior a la prueba de evaluación de usabilidad?",
    first: "Las mismas preguntas se hacen a cada individuo exactamente de la misma manera",
    second: "Estructura concisa, momento preciso y cuestiones objetivas.",
    third: "Estructura concisa y cuestiones objetivas.",
    fourth: "Momento preciso y cuestiones objetivas.",
    answer: 1,
  },
  item26: {
    id: "26",
    title: "¿Cómo se puede refinar el cuestionario de preguntas para las pruebas de evaluación?",
    first: "Elaborando un cuestionario inequívoco e imparcial.",
    second: "No es necesario refinarlo, puesto que con las propias pruebas se va modificando y adaptando.",
    third: "Elaborando un cuestionario fácil de entender y responder.",
    fourth: "Realizando una prueba piloto previa.",
    answer: 4,
  },
  item27: {
    id: "27",
    title: "¿Cuáles son las 4 etapas fundamentales de la preparación de las pruebas de usabilidad?",
    first: "Definición de objetivos, revisión de objetivos, diseño de pruebas y preparación del material.",
    second: "Definición de objetivos, análisis de usuario, diseño de pruebas y preparación del material.",
    third: "Definición de objetivos, nivel mínimo de experiencia, desarrollar la capacitación y pruebas para usuarios avanzados.",
    fourth: "Definición de objetivos, nivel mínimo de experiencia, análisis de usuario y pruebas para usuarios avanzados.",
    answer: 2,
  },
  item28: {
    id: "28",
    title: "La selección y adquisición de participantes cuyo trasfondo y habilidades sean representativos del usuario previsto para tu producto",
    first: "Es un elemento crucial del proceso de prueba.",
    second: "Es un elemento optativo del proceso de prueba.",
    third: "Es un elemento crucial del proceso de selección.",
    fourth: "Es un elemento optativo del proceso de selección.",
    answer: 1,
  },
  item29: {
    id: "29",
    title: "Al determinar el perfil del usuario",
    first: "Asegúrese de diferenciar entre el vendedor y el usuario final real",
    second: "Asegúrese de diferenciar entre el usuario y el representante final real",
    third: "Asegúrese de diferenciar entre el comprador y el usuario final real",
    fourth: "Asegúrese de diferenciar entre el desarrollador y el usuario final real",
    answer: 3,
  },
  item30: {
    id: "30",
    title: "Existen varios documentos creados en las primeras etapas del desarrollo del producto que pueden ser útiles para comenzar a generar un perfil de usuario:",
    first: "La especificación funcional y el documento de requisitos comerciales",
    second: "La especificación funcional, el documento de requisitos comerciales y la especificación de diseño o casos de uso",
    third: "La especificación funcional y la especificación de diseño o casos de uso",
    fourth: "La especificación comercial, el documento de requisitos funcionales y la especificación de diseño o casos de uso",
    answer: 2,
  },
  item31: {
    id: "31",
    title: "¿De qué manera se obtienen mejor respuestas sobre información personal (Salario, número de hijos...)?",
    first: "Número específico",
    second: "Acercarse a una de la respuestas ofrecidas",
    third: "Distintos rangos numéricos",
    fourth: "Decir que no será usado en su contra",
    answer: 3,
  },
  item32: {
    id: "32",
    title: "¿Qué conseguimos con una hoja de respuestas?",
    first: "Que el usuario responda rápidamente",
    second: "Evaluación más eficiente de participantes",
    third: "Que las respuestas correctas hagan dibujos escondidos",
    fourth: "Que la persona no piense en la respuesta que dará",
    answer: 2,
  },
  item33: {
    id: "33",
    title: "¿Qué es importante a la hora de usar Craigslist?",
    first: "Obtener el mayor número de participantes",
    second: "Que nuestro anuncio sea fácil de encontrar",
    third: "Que en el anuncio vean la remuneración obtenida por participar",
    fourth: "Evaluar meticulosamente a los participantes que se presenten",
    answer: 4,
  },
  item34: {
    id: "34",
    title: "En el proceso de captación de participantes el uso de anuncios en periódicos es:",
    first: "A día de hoy obsoleto",
    second: "Útil solo para periódicos online",
    third: "Ideal para reclutar personas menos familiarizadas con la tecnología",
    fourth: "Una pérdidad de tiempo y recursos",
    answer: 3,
  },
  item35: {
    id: "35",
    title: "¿Cuál no es un resultado que da el uso de preguntas abiertas con el candidato a participante?",
    first: "Fomenta relaciones sólidas, responsabilidad y compromiso en los participantes",
    second: "Menos probabilidad de respuestas sesgadas, permitiendo preguntas de seguimiento para aclarar detalles importantes",
    third: "Una relación más cercana con el candidato",
    fourth: "Una relación muy formal y estricta con el candidato",
    answer: 4,
  },
  item36: {
    id: "36",
    title: "¿Es recomendable incluir usuarios menos competentes en nuestras selecciones?",
    first: "Sí, ya que si estos usuarios son capaces de usar el producto la mayoría de usuarios lo serán.",
    second: "No, ya que su falta de capacidad nos atrasará en nuestra tarea",
    third: "Sí, pero no deben entrar en la selección final",
    fourth: "Estas prácticas pueden sesgar los resultados y no reflejar el uso real del producto después del lanzamiento",
    answer: 1,
  },
  item37: {
    id: "37",
    title: "¿Cuál es la principal desventaja de la técnica de pensar en voz alta?",
    first: "Puede influir involuntariamente en el comportamiento del participante.",
    second: "Puede ser poco natural y distrayente para algunos participantes.",
    third: "Puede ralentizar el proceso de pensamiento del participante.",
    fourth: "Puede ser agotador para el participante.",
    answer: 2,
  },
  item38: {
    id: "38",
    title: "¿Cuál de los siguientes es un consejo para moderar una sesión de prueba imparcialmente?",
    first: "Permitir favoritismos",
    second: "Animar a los participantes a enfocarse en sus propias experiencias.",
    third: "Ignorar las reglas establecidas",
    fourth: "No documentar los resultados",
    answer: 2,
  },
  item39: {
    id: "39",
    title: "¿Cuál de los siguientes es un consejo para evitar los efectos de sesgo de tu voz y lenguaje corporal?",
    first: "Hablar más rápido para transmitir confianza.",
    second: "Ignorar completamente tu lenguaje corporal y centrarte solo en tus palabras.",
    third: "Ser consciente de tu tono de voz y lenguaje corporal, y practicar la comunicación no verbal efectiva.",
    fourth: "Usar gestos exagerados para destacar tus puntos de vista.",
    answer: 3,
  },
  item40: {
    id: "40",
    title: "En el día de la prueba, ¿qué se debería hacer justo antes de comenzar las grabaciones?",
    first: "Pedirle a los observadores que se retiren",
    second: "Asegurarse de que el equipo de vídeo está montado y listo",
    third: "Hacerle saber al participante de que va a ser grabado",
    fourth: "Hacer debrief con el participante",
    answer: 3,
  },
  item41: {
    id: "41",
    title: "En el día de la prueba, ¿dónde hay que posicionarse mientras el participante la realiza?",
    first: "A un lado y algo alejado, para poder crear un ambiente algo más cómodo",
    second: "Detrás, para crear un ambiente cómodo y ver cómo se comporta el participante",
    third: "A un lado y muy cerca, para poder crear un ambiente algo más cómodo y ver cómo se comporta el participante",
    fourth: "Enfrente del participante, para poder ver mejor cómo se comporta",
    answer: 1,
  },
  item42: {
    id: "42",
    title: "¿Cuál de estos puntos NO pertenece a la lista de verificación una semana antes de las pruebas?",
    first: "Realizar una prueba piloto",
    second: "Pedir un congelamiento temporal del desarrollo",
    third: "Revisar el estado de sus participantes",
    fourth: "Revisar todos los equipos y el entorno de pruebas",
    answer: 3,
  },
  item43: {
    id: "43",
    title: "¿En qué consiste el debriefing?",
    first: "La exploración y revisión de las acciones o interacciones de los participantes durante la ejecución de una prueba de usabilidad",
    second: "La exploración y revisión de las acciones o interacciones de los participantes después la ejecución de una prueba de usabilidad",
    third: "La exploración y revisión de las acciones o interacciones de los participantes antes la ejecución de una prueba de usabilidad",
    fourth: "La simple revisión de las acciones o interacciones de los participantes antes la ejecución de una prueba de usabilidad",
    answer: 1,
  },
  item44: {
    id: "44",
    title: "El objetivo del debriefing con participantes…",
    first: "Aclarar el proceso de pensamiento y la lógica que subyace a las acciones de cada participantes",
    second: "Obtener una visión ampliada de la actuación del participante aprovechando las observaciones de los demás",
    third: "Evaluar la velocidad de respuesta de los participantes",
    fourth: "Comparar las respuestas de los participantes para clasificarlos",
    answer: 1,
  },
  item45: {
    id: "45",
    title: "¿Cuál es el principal objetivo al aplicar la técnica Repetición de la prueba?",
    first: "Aumentar la dificultad de la prueba para desafiar a los participantes.",
    second: "Refrescar la memoria del participante y ayudarle a recordar puntos importantes.",
    third: " Evaluar la capacidad de los participantes para enfrentar nuevas preguntas.",
    fourth: " Proporcionar a los participantes nuevas preguntas para mantener su interés.",
    answer: 2,
  },
  item46: {
    id: "46",
    title: "¿Cuál es el objetivo principal del análisis preliminar en el proceso de evaluación de usabilidad?",
    first: "Identificar áreas de mejora para que el equipo de desarrollo pueda realizar cambios en el producto.",
    second: "Identificar los problemas más críticos para que el equipo de desarrollo pueda abordarlos de inmediato.",
    third: "Asegurar que el producto cumpla con los objetivos de usabilidad establecidos.",
    fourth: "Proporcionar recomendaciones definitivas sobre cómo mejorar la usabilidad del producto.",
    answer: 2,
  },
  item47: {
    id: "47",
    title: "¿Qué datos se deben recopilar durante el proceso de análisis de datos de usabilidad?",
    first: "Datos cuantitativos, como el tiempo que tardan los participantes en completar tareas y el número de errores que cometen.",
    second: "Datos cualitativos, como los comentarios de los participantes sobre el producto.",
    third: "Datos sobre la frecuencia y tipo de sugerencias",
    fourth: "Ambos datos cuantitativos y cualitativos.",
    answer: 4,
  },
  item48: {
    id: "48",
    title: "¿Qué se destaca como importante durante la presentación de resultados, especialmente en informes preliminares? ",
    first: "La necesidad de realizar análisis exhaustivos.",
    second: "Etiquetar claramente los informes como PRELIMINAR.",
    third: "Evitar sesiones informativas con el equipo de desarrollo.",
    fourth: "No realizar ajustes basados en análisis posteriores.",
    answer: 2,
  },
  item49: {
    id: "49",
    title: "¿Qué criterio común se utiliza para determinar si una tarea es problemática en una prueba de usabilidad?",
    first: "Menos del 50% de los usuarios completan la tarea.",
    second: "Al menos el 90% de los usuarios tienen éxito en la tarea.",
    third: "Si menos del 70% de los usuarios la completan con éxito.",
    fourth: "Solo si todos los usuarios completan la tarea",
    answer: 3,
  },
  item50: {
    id: "50",
    title: "¿Cuál es el objetivo de la priorización de problemas en el análisis de datos de usabilidad?",
    first: " Ignorar problemas críticos.",
    second: " Categorizar los problemas por gravedad y frecuencia.",
    third: "Evitar asignar recursos de manera efectiva.",
    fourth: " No tener en cuenta la criticidad de los problemas.",
    answer: 2,
  },
  item51: {
    id: "51",
    title: "Después de identificar las tareas problemáticas, ¿cuál es el siguiente paso crucial en el proceso de análisis de datos?",
    first: "Continuar con más pruebas de usabilidad.",
    second: "Identificar las fuentes de error.",
    third: "Ignorar los problemas menores.",
    fourth: "Priorizar problemas por gravedad.",
    answer: 2,
  },
  item52: {
    id: "52",
    title: "Cuál debe ser la extensión de manera general de un informe",
    first: "Depende de la complejidad, pero por lo general entre 20 y 25 páginas",
    second: "Depende de la complejidad del test, unas 10 páginas",
    third: "30 páginas",
    fourth: "Más de 40 páginas",
    answer: 1,
  },
  item53: {
    id: "53",
    title: "Como tiene que ser un Resumen ejecutivo",
    first: "Un resumen las recomendaciones de la página",
    second: "Un resumen de los menús de la página",
    third: "Una sinopsis del test, con los hallazgos y recomendaciones; y escrito en 1 página como máximo.",
    fourth: "Un informe con un lenguaje técnico sobre la página",
    answer: 3,
  },
  item54: {
    id: "54",
    title: "Como tiene que ser la redacción en un informe",
    first: "Largo, específico y con lenguaje técnico difícil de comprender",
    second: "Largo y con lenguaje fácil de comprender",
    third: "Conciso y fácil de comprender para la audiencia  a la que va dirigido",
    fourth: "Conciso y con un lenguaje técnico difícil de comprender",
    answer: 3,
  },
  item55: {
    id: "55",
    title: "A la hora de hacer encuestas para obtener feedback sobre nuestro sitio, ¿Sobre qué temas deberíamos preguntar en esas encuestas?",
    first: "Sobre la usabilidad del sitio",
    second: "Sobre el contenido del sitio",
    third: "Sobre el contenido, la usabilidad del sitio y el valor de la prueba",
    fourth: "Sobre la usabilidad del sitio y el valor de la prueba",
    answer: 3,
  },
  item56: {
    id: "56",
    title: "¿Cúal es la mejor manera de implementar recomendaciones de corto y largo plazo?",
    first: "Dando más importancia a las recomendaciones a corto plazo",
    second: "La implementación a corto plazo en el tiempo pero sabiendo que hay otras recomendaciones importantes en el largo plazo",
    third: "Ingnorando el corto plazo y centrándose en las recomendaciones a largo plazo",
    fourth: "Son recomendaciones, por lo tanto no hay una mejor manera",
    answer: 2,
  },
  item57: {
    id: "57",
    title: "¿De qué habla el libro Handbook of Usability Testing a la hora de decir Sea minucioso?",
    first: "Se debe repasar todas las preguntas y problemas que desea investigar",
    second: "No dar opción a recibir feedback",
    third: "Hacer videos, auque luego no se analicen",
    fourth: "A que se tienen que estudiar de la misma manera todas las áreas de tu investigación",
    answer: 1,
  },
  item58: {
    id: "58",
    title: "¿Cuál de los siguientes tipos de entrevistas se caracteriza por permitir que el entrevistador explore temas de manera flexible, con preguntas abiertas y sin un conjunto predefinido de respuestas?",
    first: "Entrevista estructurada",
    second: "Entrevista no estructurada",
    third: "Entrevista semi-estructurada",
    fourth: "Entrevista Narrativa",
    answer: 2,
  },
  item59: {
    id: "59",
    title: "¿Cuál es una posible percepción negativa asociada específicamente con las llamadas telefónicas como modalidad de entrevista?",
    first: "Mayor cautela en la revelación de información sensible.",
    second: "Pérdida de información valiosa debido a la falta de comunicación no verbal.",
    third: "Conveniencia para participantes y entrevistadores.",
    fourth: "Posible percepción de impersonalidad en llamadas telefónicas",
    answer: 4,
  },
  item60: {
    id: "60",
    title: "¿Cuál es el propósito principal de las preguntas rompe hielo en una entrevista?",
    first: "Recopilar información específica sobre el tema central.",
    second: "Establecer una relación de confianza y facilitar la comunicación.",
    third: "Introducir el tema de discusión y dirigir la atención.",
    fourth: "Recapitular los puntos más importantes de la conversación.",
    answer: 2,
  },
  item61: {
    id: "61",
    title: "¿Cuál es un enfoque recomendado para lidiar con la posibilidad de que algunos participantes no puedan responder ciertas preguntas?",
    first: "Obligar a los participantes a elegir respuestas incluso si carecen de experiencia.",
    second: "Iniciar las entrevistas destacando la existencia de respuestas correctas e incorrectas.",
    third: "Crear un entorno donde los participantes se sientan cómodos admitiendo la falta de experiencia.",
    fourth: "Presionar a los participantes para que respondan incluso si no tienen opinión o experiencia en ciertos temas.",
    answer: 3,
  },
  item62: {
    id: "62",
    title: "¿Cuál es un factor esencial a considerar al determinar el tamaño de la muestra para sesiones de entrevistas en entornos industriales?",
    first: "La cantidad de participantes que se pueden reclutar en un corto período de tiempo.",
    second: "El número total de usuarios finales existentes.",
    third: "La naturaleza cualitativa o cuantitativa de los datos y el tamaño de la población de usuarios.",
    fourth: "La experiencia del entrevistador en la realización de entrevistas cualitativas o cuantitativas.",
    answer: 3,
  },
  item63: {
    id: "63",
    title: "¿Cuál es uno de los elementos que se destaca en la fase de introducción de una entrevista según el texto proporcionado?",
    first: "Extender la introducción por más de diez minutos para establecer una conexión más profunda.",
    second: "Solicitar al participante que resuma su experiencia antes de comenzar la entrevista.",
    third: "No mencionar la presencia de observadores para no distraer al participante.",
    fourth: "Asegurarse de que el participante sepa que es libre de marcharse en cualquier momento.",
    answer: 4,
  },
  item64: {
    id: "64",
    title: "¿Cuál es la principal función de las entrevistas de investigación de usuarios?",
    first: "Entretenimiento personal",
    second: "Obtener información sobre experiencias humanas",
    third: "Pruebas de habilidades de los entrevistadores",
    fourth: "Publicidad de productos",
    answer: 2,
  },
  item65: {
    id: "65",
    title: "¿Por qué es importante contextualizar preguntas difíciles durante una entrevista?",
    first: "Para confundir al participante",
    second: "Para revelar la curiosidad del entrevistador",
    third: "Para asegurar respuestas genuinas",
    fourth: "Para impresionar al participante",
    answer: 3,
  },
  item66: {
    id: "66",
    title: "¿Cuál es la función de las sondas en una entrevista?",
    first: "Imponer opiniones del entrevistador",
    second: "Crear distracciones",
    third: "Aclarar o ampliar respuestas del participante",
    fourth: "Rellenar silencios incómodos",
    answer: 3,
  },
  item67: {
    id: "67",
    title: "Hablando del análisis e interpretación de una entrevista, para profesionales, ¿cuándo es mejor realizar un análisis?",
    first: "Después de todas las entrevistas",
    second: "Después de cada una de las entrevistas",
    third: "Tras realizar la mitad de entrevistas",
    fourth: "Es conveniente esperar un par de días para realizarlo",
    answer: 2,
  },
  item68: {
    id: "68",
    title: "¿Cuál es el primer paso para calcular el Kappa de Cohen?",
    first: "Calcular sumas generales de filas y columnas",
    second: "Sumar acuerdos esperados debido al azar",
    third: "Calcular la concordancia esperada para cada categoría",
    fourth: "Organizar datos en una tabla de contingencia, contando acuerdos y desacuerdos",
    answer: 4,
  },
  item69: {
    id: "69",
    title: "¿Cuál de ellos NO es un buen consejo para relizar una buena entrevista?",
    first: "Toma de notas",
    second: "Grabación en vídeo",
    third: "No involucrar al equipo de producto",
    fourth: "Flexibilidad con las preguntas",
    answer: 3,
  },
  item70: {
    id: "70",
    title: "Para que una encuesta tenga más posibilidades de ser respondida se debe: ",
    first: "Insistir al usuario para que la haga",
    second: "Las encuestas siempre tienen altas posibilidades de ser respondidas",
    third: "Ser breve y fácil para el usuario",
    fourth: "Hacer la encuesta de manera presencial",
    answer: 3,
  },
  item71: {
    id: "71",
    title: "¿Qué aspecto es importante para determinar el tamaño adecuado de una muestra para una encuesta?",
    first: "Usar una plataforma de encuestas con una gran cantidad de usuarios",
    second: "El presupuesto asignado para la investigación ",
    third: "La duración de la encuesta",
    fourth: "Usar herramientas o hacer cáculos con diferentes parámetros como el número total de encuestados o el margen de error permitido",
    answer: 4,
  },
  item72: {
    id: "72",
    title: "¿Qué formato de pregunta al usuario es conveniente si queremos saber con que frecuencia utilizan nuestro servicio a largo plazo?",
    first: "Una pregunta de desarrollo sin restricciones",
    second: "Una escala con 7 respuestas posibles de una sola elección donde cada una es un plazo determinado",
    third: "Seleccionar un intervalo de tiempo que refleje tu uso a largo plazo (por ejemplo, 1 mes) de 4 posibles intervalos",
    fourth: "Una selección múltiple con los días de la semana",
    answer: 2,
  },
  item73: {
    id: "73",
    title: "En el fichero electrónico que presenta los datos de la encuesta…",
    first: "Las filas y las columnas son independientes",
    second: "Las filas y columnas representan a un único usuario",
    third: "Las filas representan los usuarios y las columnas las variables preguntadas",
    fourth: "Las columnas representan los usuarios y las filas las variables preguntadas",
    answer: 3,
  },
  item74: {
    id: "74",
    title: "En el análisis de datos, ¿por qué es importante revisar los datos en busca de anomalías?",
    first: "Para aumentar la complejidad de la investigación.",
    second: "Para garantizar que todas las respuestas sean iguales.",
    third: "Para eliminar cualquier respuesta negativa.",
    fourth: "Para identificar posibles errores o datos atípicos.",
    answer: 4,
  },
  item75: {
    id: "75",
    title: "¿Cuál es el objetivo principal al presentar visualmente los resultados de una encuesta?",
    first: "Hacer que la presentación sea más atractiva. ",
    second: "Facilitar que las personas revisen los hallazgos de un vistazo.",
    third: "Reducir la cantidad de información presentada.",
    fourth: "Impresionar a los espectadores con gráficos complejos.",
    answer: 2,
  },
  item76: {
    id: "76",
    title: "Explicitar la política de privacidad de nuestra encuesta es importante por...",
    first: "Factores exclusivamente legales",
    second: "No es importante, la mayoría de la población de la encuesta no la leerá y requiere un esfuerzo considerable",
    third: "Dará más confianza a algunos encuestados para responder sinceramente",
    fourth: "Solo es importante en medios interactivos",
    answer: 3,
  },
  item77: {
    id: "77",
    title: "Una ventaja de las encuestas postales es",
    first: "Son más rápidas",
    second: "Son más baratas",
    third: "Requieren menos tiempo del encuestado",
    fourth: "Son accesibles a una parte de los encuestados que no son tan familiares con los medios digitales",
    answer: 4,
  },
  item78: {
    id: "78",
    title: "¿Cuál no es una ventaja de las encuestas interactivas?",
    first: "Tienen una estética más minimalista",
    second: "Permiten la detección de errores",
    third: "Permiten flujos condicionales más complejos",
    fourth: "Permiten incluir indicadores de progreso",
    answer: 1,
  },
  item79: {
    id: "79",
    title: "¿Cuál es uno de los beneficios principales del método de grupo focal según la introducción?",
    first: "Mayor control sobre las respuestas de los participantes",
    second: "Mayor rapidez en la recopilación de datos",
    third: "Obtener el permiso del participante y de la empresa",
    fourth: "Estimulación de nuevas ideas a través de la dinámica grupal",
    answer: 4,
  },
  item80: {
    id: "80",
    title: "¿Por qué se sugiere evitar preguntas que inicien con [por qué] en la redacción de preguntas para un grupo focal?",
    first: "Porque generan respuestas más detalladas y útiles.",
    second: "Porque pueden incentivar a los participantes a inventar respuestas",
    third: "Porque facilitan la comprensión de las preguntas.",
    fourth: "Porque son más directas y claras en su enfoque.",
    answer: 2,
  },
  item81: {
    id: "81",
    title: "¿Cuál es el papel del moderador en un grupo focal según el texto?",
    first: "Tomar notas detalladas durante la sesión.",
    second: "Facilitar la actividad y obtener respuestas significativas.",
    third: "Realizar la grabación de video de la sesión.",
    fourth: "Presentar materiales y prototipos a los participantes.",
    answer: 2,
  },
  item82: {
    id: "82",
    title: "¿Para que se utiliza la técnica del round-robin?",
    first: "Para que el moderador pueda pasar de un tema a otro sin perder el hilo de la conversación",
    second: "Para involucrar a todo el grupo y que participen por partes",
    third: "Aumentar la participación de personas dominantes",
    fourth: "Aumentar la seriedad y estructura de la sesión",
    answer: 2,
  },
  item83: {
    id: "83",
    title: "¿Qué variante de los focus groups implica la presentación de un prototipo a los participantes, recopilando comentarios, y luego actualizando el prototipo para su revisión en sesiones adicionales?",
    first: "Focus Group Bidireccional",
    second: "The Focus Troupe",
    third: "Focus Group basado en tareas",
    fourth: "Focus Group Iterativo",
    answer: 4,
  },
  item84: {
    id: "84",
    title: "¿Cuál es el propósito de la fase de Priorización en una sesión de Brainstorming?",
    first: "Seleccionar los elementos más deseados del conjunto de ideas generadas",
    second: "Obtener datos cuantitativos mediante votaciones en papel",
    third: "Documentar detalladamente cada comentario",
    fourth: "Facilitar la interpretación de las reacciones mediante lenguaje corporal",
    answer: 1,
  },
  item85: {
    id: "85",
    title: "¿Cuándo es apropiado utilizar un diagrama de afinidad en el análisis de datos?",
    first: "Solo al presentar resultados a partes interesadas",
    second: "Para abordar temas amplios o complicados",
    third: "Exclusivamente en situaciones de diseño de productos",
    fourth: "Únicamente cuando se necesite un enfoque holístico",
    answer: 2,
  },
  item86: {
    id: "86",
    title: "¿Cuál es la regla básica importante al utilizar un diagrama de afinidad en un equipo?",
    first: "Establecer categorías preconcebidas antes de agrupar los datos",
    second: "Fomentar la participación desigual para destacar opiniones clave",
    third: "Permitir críticas constructivas durante el proceso",
    fourth: "Asegurar una participación equitativa y sin críticas",
    answer: 4,
  },
  item87: {
    id: "87",
    title: "En el caso de estudio sobre conceptos de diseño, ¿qué recomendación se hizo para abordar la participación de un usuario difícil en las sesiones de investigación de usuarios?",
    first: "Ignorar sus comentarios y seguir con la sesión",
    second: "Permitir que el usuario dificil lidere la discusión",
    third: "Pedir al usuario dificil que se retire si no cumple con las reglas básicas",
    fourth: "Designar al usuario dificil como moderador temporal",
    answer: 3,
  },
};