const data = {
  item37: {
    id: "37",
    title: "Si deseamos crear un dominio DNS de tipo alias, lo haremos mediante un registro de tipo",
    first: "A",
    second: "MX",
    third: "CNAME",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
  item38: {
    id: "38",
    title: "En una red conmutada sin existencia de VLAN's...",
    first: "Tenemos un único dominio de difusión",
    second: "Tenemos un único dominio de colisión y múltiples dominios de difusión",
    third: "Tenemos varios dominios de colisión y difusión",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item40: {
    id: "40",
    title: "Si queremos configurar una identidad IP al switch, deberemos configurarle un",
    first: "SVI",
    second: "PCI",
    third: "IPS",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
  item41: {
    id: "41",
    title: "El ID por defecto en un switch de la VLAN nativa es:",
    first: "1",
    second: "99",
    third: "1002",
    fourth: "Ninguna de las Anteriores",
    answer: 1,
  },
item42: {
    id: "42",
    title: "En el prototocolo de autenticación extensible (EAP) se hace uso de un servidor de autenticación:",
    first: "DNS",
    second: "DHCP",
    third: "RADIUS",
    fourth: "Ninguna de las Anteriores",
    answer: 3,
  },
item43: {
    id: "43",
    title: "Indique cual de las siguientes medidas es la más efectiva para proteger una LAN inalámbrica",
    first: "Camuflaje SSID",
    second: "Filtrado de direcciones MAC",
    third: "Seguridad WLAN - WPA o WPA2",
    fourth: "Todas son igualmente efectivas",
    answer: 3,
  },
item44: {
    id: "44",
    title: "La denegación de servicio es un ataque que puede ser evitado con el estándar:",
    first: "802.11a",
    second: "802.11n",
    third: "802.11g",
    fourth: "Ninguna de las anteriores",
    answer: 4,
  },
item45: {
    id: "45",
    title: "Los puntos de acceso de una red WLAN deben situarse:",
    first: "En cuartos inaccesibles",
    second: "Cerca del techo en el centro de cada area de cobertura",
    third: "En las paredes para evitar refacciones",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item46: {
    id: "46",
    title: "Indica cual de las siguientes propiedades no emite un punto de acceso en sus beacons:",
    first: "SSID",
    second: "Velocidades admitidas",
    third: "Implementación de seguridad",
    fourth: "Solicitud de conexión",
    answer: 4,
  },
item47: {
    id: "47",
    title: "Las redes inalámbricas que operan sin necesidad de puntos de acceso se denomina:",
    first: "Sin infraestructura",
    second: "Ad-hoc",
    third: "Hand-over",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item48: {
    id: "48",
    title: "En la banda de 2.4GHZ, la portadora de cada canal tiene una distancia al siguiente canal de",
    first: "5MHz",
    second: "10MHz",
    third: "25MHz",
    fourth: "50MHz",
    answer: 1,
  },
item49: {
    id: "49",
    title: "Indica cual de los siguientes estándares de Wifi permite la transferencia hasta 54Mbps y opera en la banda de 2.4GHz",
    first: "802.11a",
    second: "802.11b",
    third: "802.11g",
    fourth: "802.11n",
    answer: 3,
  },
item50: {
    id: "50",
    title: "Indique cual de las siguientes no es una característica de la definición de robustez",
    first: "Sencillez",
    second: "Escalabilidad",
    third: "Eficiencia",
    fourth: "Todas son características deseables en una red robusta",
    answer: 4,
  },
item51: {
    id: "51",
    title: "En el diseño de una red, cuando una de las premisas a cumplir es la menor latencia, se recomienda implementar una red:",
    first: "Enrutada",
    second: "Conmutada",
    third: "Segmentada",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item52: {
    id: "52",
    title: "A veces el diseño elegido en una red no viene condicionado por requerimientos no objetivos denominados",
    first: "Requerimientos de Coste",
    second: "Requerimientos Políticos y Filosóficos",
    third: "Requerimientos de Seguridad",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item53: {
    id: "53",
    title: "Respecto a la evaluación del ancho de banda necesario en una red,seleccione la afirmación errónea",
    first: "Es sencillo evaluarlo de forma previa",
    second: "Deberemos recopilar la mayor información de perfiles y volúmen de tráfico",
    third: "Es importante identificar los flujos de datos",
    fourth: "Se debe tener en cuenta la progresión de la institución donde se vaya a instalar dicha red",
    answer: 1,
  },
item54: {
    id: "54",
    title: "Seleccione la afirmación correcta",
    first: "Si el dinero gastado en construir la red es menos que el ahorro tal vez no sea necesaria",
    second: "Gracias a la tecnología de la nube, la localización de los recursos es independiente del diseño de la red",
    third: "La instalación actual de una red debe ser tenida en cuenta en el diseño de una nueva red",
    fourth: "La solución propuesta en un diseño de red debe siempre ofrecer los últimos avances tecnológicos",
    answer: 3,
  },
item55: {
    id: "55",
    title: "Indique cual de los siguientes no se trataría de un requerimiento o característica a tener en cuenta en el diseño inicial de una red.",
    first: "Coste",
    second: "Ancho de Banda",
    third: "Localización",
    fourth: "Sistemas operativos",
    answer: 4,
  },
item56: {
    id: "56",
    title: "Indica una característica errónea de la tolerancia a fallos mediante balanceo",
    first: "El equipo de backup está activo normalmente",
    second: "No existe realmente primario y Backup",
    third: "Cada elemento debe ser capaz de soportar toda la carga",
    fourth: "Disminuye la capacidad de la red",
    answer: 4,
  },
item57: {
    id: "57",
    title: "Ante la recuperación automática ante fallos, indica la afirmación errónea:",
    first: "En la recuperación externa son los elementos soft quienes gestionan la recuperación",
    second: "En la recuperación intrínseca son los propios elementos soft o hard quienes gestionan la recuperación",
    third: "La recuperación externa implica un punto adicional y único de fallos",
    fourth: "En la recuperación externa, un mal diagnostico del elemento provoca malas acciones",
    answer: 1,
  },
item58: {
    id: "58",
    title: "Indique la afirmación errónea",
    first: "A mayor redundancia , mayor complejidad",
    second: "El rendimiento siempre se mejora con elementos redundantes",
    third: " La complejidad en administración puede ser contraproducente",
    fourth: "Las redundancias pueden crecer exponencialmente en dispositivos de acceso",
    answer: 2,
  },
item59: {
    id: "59",
    title: "Respecto a la redundancia en las redes indique la afirmación errónea",
    first: "La duplicidad de los elementos soluciona todos los problemas",
    second: "La redundancia ayuda en tareas de mantenimiento",
    third: "El rendimiento se mejora sólo si se permite la carga compartida de trabajo.",
    fourth: "Es recomendable duplicar los elementos clave en la red para garantizar la fiabilidad",
    answer: 1,
  },
  item60: {
    id: "60",
    title: "Respecto a la definición de Fiabilidad , indique la respuesta",
    first: "Los dispositivos de red son los únicos elementos destinados a ofrecer los mecanismos para garantizar la fiabilidad",
    second: "Una red fiable debe incluir tolerancia a fallos",
    third: "Una red fiable debe soportar los picos de carga.",
    fourth: "La red debe ser fiable para cualquier elemento de la misma.",
    answer: 1,
  },
item61: {
    id: "61",
    title: "Indica cual de las siguientes no es una característica de un switch de la capa de nucleo",
    first: "Componentes redundantes",
    second: "Gigabit/ 10Gigabit Ethernet",
    third: "Agregado de enlaces",
    fourth: "Políticas de seguridad/Listas de Acceso",
    answer: 4,
  },
item62: {
    id: "62",
    title: "El proceso de medición del uso del ancho de banda en una red y el análisis de datos con el fin de lograr ajustes del rendimiento, se denomina",
    first: "Análisis del flujo de tráfico",
    second: "nálisis de la escalabilidad de la red",
    third: "Análisis de las perdidas de datos",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
item63: {
    id: "63",
    title: "Cuando se permite que se combinen los enlaces de puerto de switches múltiples a fin de lograr un rendimiento superior entre los switches, se denomina",
    first: "Agregado de ancho de banda",
    second: "Diámetro de la red",
    third: "Redundancia",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
item64: {
    id: "64",
    title: "El protocolo Cisco que permite mantener una instancia de STP para cada VLAN configurada en la red, se denomina:",
    first: "STP",
    second: "TCP",
    third: "VTP",
    fourth: "PVST",
    answer: 4,
  },
item65: {
    id: "65",
    title: Indica cual de las siguientes no es una característica de la definición de robustez",
    first: "Sencillez",
    second: "Escalabilidad",
    third: "Eficiencia",
    fourth: "Todas son características deseables en una red robusta",
    answer: 4,
  },
item66: {
    id: "66",
    title: "El conmutador que reenvía publicaciones VTP y que procesa la configuración de VTP recibida se denomina",
    first: "VTP Transparernte",
    second: "Cliente VTP",
    third: "Servidor VTP",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item67: {
    id: "67",
    title: "Indica cual de los siguientes no es un beneficio obtenido directamente del uso de redes jerarquicas",
    first: "Escalabilidad",
    second: "Rendimiento",
    third: "Seguridad",
    fourth: "Ninguna de las anteriores",
    answer: 4,
  },
item68: {
    id: "68",
    title: "La red debe detectar los problemas existentes y activar los dispositivos de backup de forma automática. Dentro de los mecanismos de nivel 2, se utiliza:a",
    first: "Spanning Tree",
    second: "VLANs",
    third: "Direccionamiento IP",
    fourth: "Ninguna de las anteriores",
    answer: 1,
  },
item69: {
    id: "69",
    title: "Si la asignación de la VLAN de un puerto se realiza por el puerto del Switch al está conectado un dispositivo, nos encontramos ante un modo de pertenencia de ...",
    first: "VLAN dinámica",
    second: "VLAN estática",
    third: "VLAN física",
    fourth: "Ninguna de las anteriores",
    answer: 2,
  },
item70: {
    id: "70",
    title: "Respecto al diseño de una red, indica la afirmación errónea:",
    first: "Se debe considerar dónde se ubican los medios de almacenamiento y los servidores de datos para determinar el impacto del tráfico en la red.",
    second: "El tráfico entre servidor y servidor es el tráfico generado entre los dispositivos de almacenamiento de datos en la red.",
    third: "Los servidores que necesitan acceso frecuente a ciertos recursos se deben ubicar a muy corta distancia",
    fourth: "Los switches seleccionados para los centros de datos suelen ser del mismo tipo que el resto de switches de acceso,
    answer: 4,
  },
item71: {
    id: "71",
    title: "El número de puertos disponibles en un switch se denomina:",
    first: "Agregado de Puertos",
    second: "Desempeño de Puertos",
    third: "Densidad de Puertos",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
item72: {
    id: "72",
    title: "Cuando el tráfico de la red no puede ingresar ni salir del puerto, sin incluir las tramas de unidad de datos del protocolo de puentes (BPDU) utilizadas por STP para evitar bucles, el puerto se considera:",
    first: "Activo",
    second: "Aprendizaje",
    third: "Bloqueado",
    fourth: "Ninguna de las anteriores",
    answer: 3,
  },
};
